import { Product } from "./types";

export const PRODUCTS: Product[] = [
  // SOUND CATEGORY - DJ SETUPS
  {
    id: "sound-dj-1",
    name: "DJ Setup Single Bin",
    category: "sound",
    subCategory: "DJ's Setup",
    price: 15000,
    setupCharges: 2000,
    deliveryCharges: 1500,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
      pricing: {
        hourly: 3000,
        daily: 20000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description:
      "Complete DJ setup with single pin configuration, ideal for small to medium gatherings of up to 200 people.",
    specifications: [
      "2000W RMS total output",
      "12-channel mixing console",
      "2 top speakers with stands",
      "2 subwoofers",
      "Professional DJ console",
      "Basic LED lighting setup",
      "All necessary cables and connections",
      "Backup power solutions",
    ],
    available: true,
  },
  {
    id: "sound-dj-2",
    name: "DJ Setup Double Bin",
    category: "sound",
    subCategory: "DJ's Setup",
    price: 25000,
    setupCharges: 3000,
    deliveryCharges: 2000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
      pricing: {
        hourly: 4500,
        daily: 30000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description:
      "Professional double pin DJ setup suitable for large events and weddings with up to 500 people.",
    specifications: [
      "4000W RMS total output",
      "16-channel mixing console",
      "4 top speakers with stands",
      "4 subwoofers",
      "Professional DJ console with effects",
      "Advanced LED lighting system",
      "Wireless microphones (2)",
      "Complete cable management",
      "Backup equipment included",
    ],
    available: true,
  },

  // DECOR CATEGORY - SPECIAL EFFECTS
  {
    id: "decor-fx-1",
    name: "CO2 Jets",
    category: "decor",
    subCategory: "Special Effects",
    price: 8000,
    setupCharges: 1500,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "2 hours",
      standard: "4 hours",
      pricing: {
        hourly: 2000,
        daily: 12000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description:
      "High-impact CO2 jet effects perfect for dramatic moments and dance floors.",
    specifications: [
      "Set of 4 CO2 jets",
      "DMX controlled system",
      "CO2 cylinder included",
      "Professional operator",
      "30-second continuous blast capability",
      "Wireless remote control",
      "Safety barriers included",
    ],
    available: true,
  },
  {
    id: "decor-fx-2",
    name: "Cold Fire Package",
    category: "decor",
    subCategory: "Special Effects",
    price: 12000,
    setupCharges: 2000,
    deliveryCharges: 1500,
    rentalDuration: {
      minimum: "2 hours",
      standard: "4 hours",
      pricing: {
        hourly: 3000,
        daily: 15000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description:
      "Safe indoor pyrotechnic effects creating stunning fire displays without heat.",
    specifications: [
      "6 cold fire units",
      "DMX controller included",
      "Trained operator",
      "Safety equipment",
      "Indoor and outdoor compatible",
      "Multiple firing patterns",
      "Emergency shutdown system",
    ],
    available: true,
  },

  // ARTISTS CATEGORY
  {
    id: "artist-1",
    name: "Bridal Makeup Package",
    category: "artists",
    subCategory: "Makeup",
    price: 15000,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "3 hours",
      standard: "4 hours",
      pricing: {
        hourly: 5000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1630779374222-d8fc71997efb?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1604430456280-43f652c497aa?auto=format&fit=crop&q=80",
    ],
    description:
      "Complete bridal makeup service including hair styling and draping.",
    specifications: [
      "HD makeup application",
      "Professional hair styling",
      "Saree or outfit draping",
      "False lashes included",
      "Touch-up kit provided",
      "Trial session available",
      "Premium branded products used",
      "Assistant makeup artist included",
    ],
    available: true,
  },

  // TRANSPORTATION CATEGORY
  {
    id: "transport-1",
    name: "Premium Wedding Car",
    category: "transportation",
    subCategory: "Cars",
    price: 10000,
    setupCharges: 1000, // for decoration
    deliveryCharges: 1500,
    rentalDuration: {
      minimum: "4 hours",
      standard: "8 hours",
      pricing: {
        hourly: 2000,
        daily: 15000,
      },
    },
    image: [
      "https://i.postimg.cc/hG3Fg9tG/wedding-car-one.jpg",
      "https://i.postimg.cc/hG3Fg9tG/wedding-car-one.jpg",
    ],
    description:
      "Luxury car service with professional chauffeur and premium decoration.",
    specifications: [
      "Premium sedan (Mercedes/BMW/Audi/Jaguar)",
      "Professional uniformed chauffeur",
      "Basic floral decoration included",
      // "Red carpet service",
      "Fully air-conditioned",
      "Complimentary water bottles",
      // "Fuel included for standard duration",
      "Insurance coverage included",
      "Backup vehicle on standby",
    ],
    available: true,
  },
  {
    id: "transport-2",
    name: "Traditional Baggi/Chariot",
    category: "transportation",
    subCategory: "Special",
    price: 15000,
    setupCharges: 2000,
    deliveryCharges: 3000,
    rentalDuration: {
      minimum: "2 hours",
      standard: "4 hours",
      pricing: {
        hourly: 4000,
        daily: 25000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description:
      "Traditional horse-drawn chariot with royal decoration for wedding ceremonies.",
    specifications: [
      "Decorated royal chariot",
      "Trained horse with handler",
      "Professional chariot driver",
      "Elaborate floral decoration",
      "LED lighting setup",
      "Safety railings and steps",
      "Support staff (2 persons)",
      "Backup transportation arranged",
      "Traditional music system included",
    ],
    available: true,
  },

  // DECOR - LIGHTING CATEGORY
  {
    id: "decor-light-1",
    name: "LED Dance Floor",
    category: "decor",
    subCategory: "Lighting",
    price: 25000,
    setupCharges: 5000,
    deliveryCharges: 3000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
      pricing: {
        hourly: 5000,
        daily: 35000,
      },
    },
    image: [
      "https://i.postimg.cc/wTZjWVFV/LED-dance-floor-3.jpg",
      "https://i.postimg.cc/QMrxDd2K/led-dance-floor-1.jpg",
      "https://i.postimg.cc/qvKMW35d/LED-dance-floor-2.jpg",
    ],
    description:
      "Interactive LED dance floor with multiple patterns and color combinations.",
    specifications: [
      "16x16 ft standard size (customizable)",
      "RGB LED panels",
      "Multiple pattern animations",
      "Sound-reactive modes",
      "DMX controller included",
      "Non-slip surface",
      "Waterproof rating IP65",
      "Technical operator included",
      "Backup panels available",
      "Setup time: 3 hours",
    ],
    available: true,
  },
  {
    id: "decor-light-2",
    name: "Premium Backdrop Lighting",
    category: "decor",
    subCategory: "Lighting",
    price: 18000,
    setupCharges: 3000,
    deliveryCharges: 2000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
      pricing: {
        hourly: 3500,
        daily: 25000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&q=80",
    ],
    description:
      "Complete backdrop lighting solution with premium effects and controls.",
    specifications: [
      "20x12 ft standard coverage",
      "RGB LED wall washers",
      "Moving head lights (4 units)",
      "Par LED lights (8 units)",
      "DMX controller with programs",
      "Wireless control system",
      "Multiple scene settings",
      "Emergency backup lights",
      "Technical operator included",
      "Setup time: 2 hours",
    ],
    available: true,
  },

  // SUPPORT STAFF CATEGORY
  {
    id: "staff-1",
    name: "Professional Chauffeur",
    category: "support-staff",
    subCategory: "Drivers",
    price: 2000,
    deliveryCharges: 500,
  },

  // SOUND - LIVE SOUND EQUIPMENT
  {
    id: "sound-live-1",
    name: "Live Band Setup",
    category: "sound",
    subCategory: "Live Sound",
    price: 35000,
    setupCharges: 5000,
    deliveryCharges: 3000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
      pricing: {
        hourly: 6000,
        daily: 45000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description: "Complete live band setup with professional sound equipment.",
    specifications: [
      "32-channel digital mixer",
      "Full drum kit microphone set",
      "Wireless microphones (4 units)",
      "Stage monitors (4 units)",
      "Main speakers with amplifiers",
      "DI boxes for instruments",
      "Complete cable management",
      "Sound engineer included",
      "Backup equipment available",
      "Setup time: 3 hours",
    ],
    available: true,
  },
  {
    id: "sound-live-2",
    name: "Nadaswaram Group",
    category: "sound",
    subCategory: "Live Sound",
    price: 15000,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "2 hours",
      standard: "4 hours",
      pricing: {
        hourly: 4000,
        daily: 25000,
      },
    },
    image: [
      "https://i.postimg.cc/zvfGQ29d/Nadaswaram-Group.jpg",
      "https://i.postimg.cc/j28LdYH0/Nadaswaram-Group-2.jpg",
    ],
    description: "Traditional Nadaswaram group for auspicious ceremonies.",
    specifications: [
      "Professional 5-member team",
      "Traditional costumes",
      "2 Nadaswaram players",
      "2 Thavil players",
      "1 Shruti box player",
      "Sound system included",
      "Traditional and modern repertoire",
      "Experienced in wedding ceremonies",
      "Backup artists available",
    ],
    available: true,
  },

  // DECOR - FURNITURE
  {
    id: "decor-furn-1",
    name: "Premium Sofa Set",
    category: "decor",
    subCategory: "Furniture",
    price: 12000,
    setupCharges: 2000,
    deliveryCharges: 2500,
    rentalDuration: {
      minimum: "24 hours",
      standard: "24 hours",
      pricing: {
        daily: 12000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description: "Luxury sofa set for wedding stage and VIP areas.",
    specifications: [
      "3-seater royal sofa (2 units)",
      "Single-seater chairs (4 units)",
      "Premium fabric upholstery",
      "Matching center tables",
      "Side tables (4 units)",
      "Decorative cushions included",
      "Carpet area included",
      "Setup and arrangement",
      "Backup furniture available",
    ],
    available: true,
  },
  {
    id: "decor-furn-2",
    name: "Complete Stage Setup",
    category: "decor",
    subCategory: "Furniture",
    price: 45000,
    setupCharges: 8000,
    deliveryCharges: 5000,
    rentalDuration: {
      minimum: "24 hours",
      standard: "24 hours",
      pricing: {
        daily: 45000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description:
      "Complete wedding stage setup with premium furniture and decor.",
    specifications: [
      "24x16 ft raised platform",
      "Premium backdrop with lighting",
      "Royal sofa set for couple",
      "Side seating arrangements",
      "Floral decoration",
      "LED accent lighting",
      "Carpet and walkway",
      "Photo opportunity areas",
      "Setup time: 6 hours",
      "Professional decor team",
    ],
    available: true,
  },

  // DECOR - SPECIAL EFFECTS
  {
    id: "decor-fx-3",
    name: "Bubble Show Package",
    category: "decor",
    subCategory: "Special Effects",
    price: 8000,
    setupCharges: 1500,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "2 hours",
      standard: "4 hours",
      pricing: {
        hourly: 2000,
        daily: 12000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description: "Professional bubble show with multiple effects and machines.",
    specifications: [
      "Professional bubble machines (3 units)",
      "Smoke bubble capability",
      "LED bubble effects",
      "Special bubble solution",
      "Multiple pattern programs",
      "DMX controller included",
      "Trained operator",
      "Indoor/outdoor compatible",
      "Setup time: 1 hour",
    ],
    available: true,
  },
  {
    id: "decor-fx-4",
    name: "Flower Shower System",
    category: "decor",
    subCategory: "Special Effects",
    price: 12000,
    setupCharges: 2000,
    deliveryCharges: 1500,
    rentalDuration: {
      minimum: "2 hours",
      standard: "4 hours",
      pricing: {
        hourly: 3000,
        daily: 15000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description: "Automated flower shower system for special moments.",
    specifications: [
      "4 flower shower units",
      "Fresh flower petals included",
      "Remote controlled operation",
      "Multiple shower patterns",
      "Coverage area: 400 sq ft",
      "Indoor/outdoor compatible",
      "Setup with truss system",
      "Operator included",
      "Setup time: 2 hours",
    ],
    available: true,
  },

  // ARTISTS - MEHENDI & MAKEUP
  {
    id: "artist-mehendi-1",
    name: "Premium Bridal Mehendi",
    category: "artists",
    subCategory: "Mehendi",
    price: 15000,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
      pricing: {
        hourly: 3000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1630779374222-d8fc71997efb?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1604430456280-43f652c497aa?auto=format&fit=crop&q=80",
    ],
    description: "Premium bridal mehendi service with exclusive designs.",
    specifications: [
      "Expert mehendi artist",
      "Premium natural mehendi cones",
      "Exclusive design catalog",
      "Both hands and feet coverage",
      "Arabic and Indian designs",
      "Duration: 3-4 hours",
      "Touch-up service included",
      "Natural darkening tips",
      "Aftercare kit provided",
    ],
    available: true,
  },
  {
    id: "artist-hair-1",
    name: "Professional Hair Styling",
    category: "artists",
    subCategory: "Hair Styling",
    price: 8000,
    deliveryCharges: 500,
    rentalDuration: {
      minimum: "2 hours",
      standard: "3 hours",
      pricing: {
        hourly: 3000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description: "Professional hair styling service for all occasions.",
    specifications: [
      "Expert hair stylist",
      "Premium styling products",
      "Heat protection treatment",
      "Hair accessories included",
      "Multiple style options",
      "Pre-event consultation",
      "Touch-up kit provided",
      "Style duration: 6-8 hours",
      "Extension services available",
    ],
    available: true,
  },

  // SUPPORT STAFF - HOSPITALITY
  {
    id: "staff-hosp-1",
    name: "Welcome Staff Team",
    category: "support-staff",
    subCategory: "Hospitality",
    price: 12000,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
      pricing: {
        hourly: 2000,
        daily: 15000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description: "Professional welcome staff team for events.",
    specifications: [
      "6 trained staff members",
      "Professional uniforms",
      "Guest management expertise",
      "Multi-lingual capabilities",
      "Coordination with event team",
      "Welcome drink service",
      "Guest list management",
      "Emergency handling trained",
      "Backup staff available",
    ],
    available: true,
  },
  {
    id: "staff-security-1",
    name: "Event Security Team",
    category: "support-staff",
    subCategory: "Security",
    price: 10000,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "6 hours",
      standard: "8 hours",
      pricing: {
        hourly: 1500,
        daily: 12000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description: "Professional security team for event safety.",
    specifications: [
      "4 trained security guards",
      "1 supervisor",
      "Professional uniforms",
      "Security equipment",
      "Crowd management trained",
      "Emergency protocols",
      "CCTV monitoring",
      "Parking management",
      "VIP security available",
    ],
    available: true,
  },

  // DECOR - EVENT DECOR
  {
    id: "decor-event-1",
    name: "Haldi Ceremony Setup",
    category: "decor",
    subCategory: "Event Decor",
    price: 25000,
    setupCharges: 3000,
    deliveryCharges: 2000,
    rentalDuration: {
      minimum: "6 hours",
      standard: "8 hours",
      pricing: {
        daily: 25000,
      },
    },
    image: [
      "https://i.postimg.cc/66RZStdQ/Basic-in-house-Mehndi-backdrop-decor.jpg",
      "https://i.postimg.cc/4y4YgxhQ/def82651-f974-40f3-b528-9f50e0a2207c.jpg",
      "https://i.postimg.cc/44wK1VrL/c8f80ca3-8587-433c-8925-e6f5c16f1123.jpg",
    ],
    description:
      "Complete Haldi ceremony decoration with traditional elements.",
    specifications: [
      "Traditional mandap setup",
      "Floral decoration",
      "Seating arrangement for 50 people",
      "Cushions and low seating",
      "Backdrop decoration",
      "Props for photography",
      "Lighting arrangement",
      "Traditional elements",
      "Setup time: 4 hours",
      "Cleanup included",
    ],
    available: true,
  },
  {
    id: "decor-event-2",
    name: "Reception Stage Package",
    category: "decor",
    subCategory: "Event Decor",
    price: 75000,
    setupCharges: 10000,
    deliveryCharges: 5000,
    rentalDuration: {
      minimum: "12 hours",
      standard: "24 hours",
      pricing: {
        daily: 75000,
      },
    },
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ],
    description: "Premium reception stage and venue decoration package.",
    specifications: [
      "30x20 ft stage setup",
      "Premium backdrop design",
      "LED wall integration",
      "Floral arrangements",
      "Premium furniture set",
      "Walkway decoration",
      "Photo booth area",
      "Complete venue lighting",
      "Setup time: 8 hours",
      "Professional decor team",
    ],
    available: true,
  },

  // PHOTOGRAPHY PACKAGES
  {
    id: "photo-1",
    name: "Premium Wedding Photography",
    category: "photography",
    subCategory: "Wedding",
    price: 75000,
    deliveryCharges: 2000,
    rentalDuration: {
      minimum: "12 hours",
      standard: "Full day",
      pricing: {
        daily: 75000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80",
    ],
    description:
      "Complete wedding photography package with premium equipment and experienced team.",
    specifications: [
      "2 Professional photographers",
      "1 Videographer",
      "1 Drone operator",
      "4K Video recording",
      "Same day edit highlights",
      "Full HD wedding film",
      "500+ edited photos",
      "Premium photo album",
      "Online gallery access",
      "Raw footage provided",
      "Equipment: Sony A7 series cameras",
      "Backup equipment available",
    ],
    available: true,
  },
  {
    id: "photo-2",
    name: "Pre-Wedding Shoot",
    category: "photography",
    subCategory: "Pre-Wedding",
    price: 35000,
    deliveryCharges: 2000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
      pricing: {
        hourly: 6000,
        daily: 35000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80",
    ],
    description:
      "Creative pre-wedding photoshoot with multiple locations and concepts.",
    specifications: [
      "1 Lead photographer",
      "1 Assistant photographer",
      "Multiple locations covered",
      "Outfit suggestions",
      "Professional editing",
      "200+ edited photos",
      "Cinematic video trailer",
      "Makeup artist available",
      "Props included",
      "Location scouting",
      "Weather backup dates",
    ],
    available: true,
  },

  // SUPPORT STAFF - SPECIALIZED
  {
    id: "staff-1",
    name: "Professional Valet Team",
    category: "support-staff",
    subCategory: "Valet",
    price: 15000,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "6 hours",
      standard: "8 hours",
      pricing: {
        hourly: 2000,
        daily: 20000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description: "Professional valet parking service team for events.",
    specifications: [
      "5 Trained valet drivers",
      "1 Supervisor",
      "Uniformed staff",
      "Insurance coverage",
      "Parking tokens system",
      "Traffic management",
      "Key management system",
      "Emergency vehicle support",
      "Coordination with security",
      "Backup staff available",
    ],
    available: true,
  },
  {
    id: "staff-2",
    name: "Event Hostess Team",
    category: "support-staff",
    subCategory: "Hostess",
    price: 12000,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
      pricing: {
        hourly: 2500,
        daily: 15000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description: "Professional hostess team for corporate and social events.",
    specifications: [
      "4 Trained hostesses",
      "Professional attire",
      "Guest reception",
      "Multi-lingual capabilities",
      "Event coordination",
      "VIP guest handling",
      "Protocol management",
      "Emergency handling trained",
      "Grooming standards",
      "Backup staff available",
    ],
    available: true,
  },
  {
    id: "staff-3",
    name: "Catering Service Staff",
    category: "support-staff",
    subCategory: "Catering",
    price: 18000,
    deliveryCharges: 1500,
    rentalDuration: {
      minimum: "6 hours",
      standard: "8 hours",
      pricing: {
        hourly: 2500,
        daily: 18000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description: "Professional catering service staff for events.",
  },
];
