import { Product } from "./types";

export const PRODUCTS: Product[] = [
  // SOUND CATEGORY - DJ SETUPS
  {
    id: "sound-dj-1",
    name: "DJ Setup Single Bin",
    category: "sound",
    subCategory: "DJ's Setup",
    price: 15000,
    setupCharges: 2000,
    deliveryCharges: 1500,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
      pricing: {
        hourly: 3000,
        daily: 20000,
      },
    },
    image: [
      "https://image.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description:
      "Complete DJ setup with single pin configuration, ideal for small to medium gatherings of up to 200 people.",
    specifications: [
      "2000W RMS total output",
      "12-channel mixing console",
      "2 top speakers with stands",
      "2 subwoofers",
      "Professional DJ console",
      "Basic LED lighting setup",
      "All necessary cables and connections",
      "Backup power solutions",
    ],
    available: true,
  },
  {
    id: "sound-dj-2",
    name: "DJ Setup Double Bin",
    category: "sound",
    subCategory: "DJ's Setup",
    price: 25000,
    setupCharges: 3000,
    deliveryCharges: 2000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
      pricing: {
        hourly: 4500,
        daily: 30000,
      },
    },
    image: [
      "https://myutsav.s3.ap-south-1.amazonaws.com/double-bin-sound-system-rental-500x500.webp",
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description:
      "Professional double pin DJ setup suitable for large events and weddings with up to 500 people.",
    specifications: [
      "4000W RMS total output",
      "16-channel mixing console",
      "4 top speakers with stands",
      "4 subwoofers",
      "Professional DJ console with effects",
      "Advanced LED lighting system",
      "Wireless microphones (2)",
      "Complete cable management",
      "Backup equipment included",
    ],
    available: true,
  },

  // DECOR CATEGORY - SPECIAL EFFECTS
  {
    id: "decor-fx-1",
    name: "CO2 Jets",
    category: "decor",
    subCategory: "Special Effects",
    price: 8000,
    setupCharges: 1500,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "2 hours",
      standard: "4 hours",
      pricing: {
        hourly: 2000,
        daily: 12000,
      },
    },
    image: [
      "https://myutsav.s3.ap-south-1.amazonaws.com/Sharpies-one",
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description:
      "High-impact CO2 jet effects perfect for dramatic moments and dance floors.",
    specifications: [
      "Set of 4 CO2 jets",
      "DMX controlled system",
      "CO2 cylinder included",
      "Professional operator",
      "30-second continuous blast capability",
      "Wireless remote control",
      "Safety barriers included",
    ],
    available: true,
  },
  {
    id: "decor-fx-2",
    name: "Cold Fire Package",
    category: "decor",
    subCategory: "Special Effects",
    price: 12000,
    setupCharges: 2000,
    deliveryCharges: 1500,
    rentalDuration: {
      minimum: "2 hours",
      standard: "4 hours",
      pricing: {
        hourly: 3000,
        daily: 15000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description:
      "Safe indoor pyrotechnic effects creating stunning fire displays without heat.",
    specifications: [
      "6 cold fire units",
      "DMX controller included",
      "Trained operator",
      "Safety equipment",
      "Indoor and outdoor compatible",
      "Multiple firing patterns",
      "Emergency shutdown system",
    ],
    available: true,
  },

  // ARTISTS CATEGORY
  {
    id: "artist-1",
    name: "Bridal Makeup Package",
    category: "artists",
    subCategory: "Makeup",
    price: 15000,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "3 hours",
      standard: "4 hours",
      pricing: {
        hourly: 5000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1630779374222-d8fc71997efb?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1604430456280-43f652c497aa?auto=format&fit=crop&q=80",
    ],
    description:
      "Complete bridal makeup service including hair styling and draping.",
    specifications: [
      "HD makeup application",
      "Professional hair styling",
      "Saree or outfit draping",
      "False lashes included",
      "Touch-up kit provided",
      "Trial session available",
      "Premium branded products used",
      "Assistant makeup artist included",
    ],
    available: true,
  },

  // TRANSPORTATION CATEGORY
  {
    id: "transport-1",
    name: "Premium Wedding Car",
    category: "transportation",
    subCategory: "Cars",
    price: 10000,
    setupCharges: 1000, // for decoration
    deliveryCharges: 1500,
    rentalDuration: {
      minimum: "4 hours",
      standard: "8 hours",
      pricing: {
        hourly: 2000,
        daily: 15000,
      },
    },
    image: [
      "https://i.postimg.cc/hG3Fg9tG/wedding-car-one.jpg",
      "https://i.postimg.cc/hG3Fg9tG/wedding-car-one.jpg",
    ],
    description:
      "Luxury car service with professional chauffeur and premium decoration.",
    specifications: [
      "Premium sedan (Mercedes/BMW/Audi/Jaguar)",
      "Professional uniformed chauffeur",
      "Basic floral decoration included",
      // "Red carpet service",
      "Fully air-conditioned",
      "Complimentary water bottles",
      // "Fuel included for standard duration",
      "Insurance coverage included",
      "Backup vehicle on standby",
    ],
    available: true,
  },
  {
    id: "transport-2",
    name: "Traditional Baggi/Chariot",
    category: "transportation",
    subCategory: "Special",
    price: 15000,
    setupCharges: 2000,
    deliveryCharges: 3000,
    rentalDuration: {
      minimum: "2 hours",
      standard: "4 hours",
      pricing: {
        hourly: 4000,
        daily: 25000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description:
      "Traditional horse-drawn chariot with royal decoration for wedding ceremonies.",
    specifications: [
      "Decorated royal chariot",
      "Trained horse with handler",
      "Professional chariot driver",
      "Elaborate floral decoration",
      "LED lighting setup",
      "Safety railings and steps",
      "Support staff (2 persons)",
      "Backup transportation arranged",
      "Traditional music system included",
    ],
    available: true,
  },

  // DECOR - LIGHTING CATEGORY
  {
    id: "decor-light-1",
    name: "LED Dance Floor",
    category: "decor",
    subCategory: "Lighting",
    price: 25000,
    setupCharges: 5000,
    deliveryCharges: 3000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
      pricing: {
        hourly: 5000,
        daily: 35000,
      },
    },
    image: [
      "https://i.postimg.cc/wTZjWVFV/LED-dance-floor-3.jpg",
      "https://i.postimg.cc/QMrxDd2K/led-dance-floor-1.jpg",
      "https://i.postimg.cc/qvKMW35d/LED-dance-floor-2.jpg",
    ],
    description:
      "Interactive LED dance floor with multiple patterns and color combinations.",
    specifications: [
      "16x16 ft standard size (customizable)",
      "RGB LED panels",
      "Multiple pattern animations",
      "Sound-reactive modes",
      "DMX controller included",
      "Non-slip surface",
      "Waterproof rating IP65",
      "Technical operator included",
      "Backup panels available",
      "Setup time: 3 hours",
    ],
    available: true,
  },
  {
    id: "decor-light-2",
    name: "Premium Backdrop Lighting",
    category: "decor",
    subCategory: "Lighting",
    price: 18000,
    setupCharges: 3000,
    deliveryCharges: 2000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
      pricing: {
        hourly: 3500,
        daily: 25000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&q=80",
    ],
    description:
      "Complete backdrop lighting solution with premium effects and controls.",
    specifications: [
      "20x12 ft standard coverage",
      "RGB LED wall washers",
      "Moving head lights (4 units)",
      "Par LED lights (8 units)",
      "DMX controller with programs",
      "Wireless control system",
      "Multiple scene settings",
      "Emergency backup lights",
      "Technical operator included",
      "Setup time: 2 hours",
    ],
    available: true,
  },

  // SUPPORT STAFF CATEGORY

  // SOUND - LIVE SOUND EQUIPMENT
  {
    id: "sound-live-1",
    name: "Live Band Setup",
    category: "sound",
    subCategory: "Live Sound",
    price: 35000,
    setupCharges: 5000,
    deliveryCharges: 3000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
      pricing: {
        hourly: 6000,
        daily: 45000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description: "Complete live band setup with professional sound equipment.",
    specifications: [
      "32-channel digital mixer",
      "Full drum kit microphone set",
      "Wireless microphones (4 units)",
      "Stage monitors (4 units)",
      "Main speakers with amplifiers",
      "DI boxes for instruments",
      "Complete cable management",
      "Sound engineer included",
      "Backup equipment available",
      "Setup time: 3 hours",
    ],
    available: true,
  },

  {
    id: "sound-live-2",
    name: "Nadaswaram Group",
    category: "sound",
    subCategory: "Live Sound",
    price: 15000,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "2 hours",
      standard: "4 hours",
      pricing: {
        hourly: 4000,
        daily: 25000,
      },
    },
    image: [
      "https://i.postimg.cc/zvfGQ29d/Nadaswaram-Group.jpg",
      "https://i.postimg.cc/j28LdYH0/Nadaswaram-Group-2.jpg",
    ],
    description: "Traditional Nadaswaram group for auspicious ceremonies.",
    specifications: [
      "Professional 5-member team",
      "Traditional costumes",
      "2 Nadaswaram players",
      "2 Thavil players",
      "1 Shruti box player",
      "Sound system included",
      "Traditional and modern repertoire",
      "Experienced in wedding ceremonies",
      "Backup artists available",
    ],
    available: true,
  },

  // DECOR - FURNITURE
  {
    id: "decor-furn-1",
    name: "Premium Sofa Set",
    category: "decor",
    subCategory: "Furniture",
    price: 12000,
    setupCharges: 2000,
    deliveryCharges: 2500,
    rentalDuration: {
      minimum: "24 hours",
      standard: "24 hours",
      pricing: {
        daily: 12000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description: "Luxury sofa set for wedding stage and VIP areas.",
    specifications: [
      "3-seater royal sofa (2 units)",
      "Single-seater chairs (4 units)",
      "Premium fabric upholstery",
      "Matching center tables",
      "Side tables (4 units)",
      "Decorative cushions included",
      "Carpet area included",
      "Setup and arrangement",
      "Backup furniture available",
    ],
    available: true,
  },
  {
    id: "decor-furn-2",
    name: "Complete Stage Setup",
    category: "decor",
    subCategory: "Furniture",
    price: 45000,
    setupCharges: 8000,
    deliveryCharges: 5000,
    rentalDuration: {
      minimum: "24 hours",
      standard: "24 hours",
      pricing: {
        daily: 45000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description:
      "Complete wedding stage setup with premium furniture and decor.",
    specifications: [
      "24x16 ft raised platform",
      "Premium backdrop with lighting",
      "Royal sofa set for couple",
      "Side seating arrangements",
      "Floral decoration",
      "LED accent lighting",
      "Carpet and walkway",
      "Photo opportunity areas",
      "Setup time: 6 hours",
      "Professional decor team",
    ],
    available: true,
  },

  // DECOR - SPECIAL EFFECTS
  {
    id: "decor-fx-3",
    name: "Bubble Show Package",
    category: "decor",
    subCategory: "Special Effects",
    price: 8000,
    setupCharges: 1500,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "2 hours",
      standard: "4 hours",
      pricing: {
        hourly: 2000,
        daily: 12000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description: "Professional bubble show with multiple effects and machines.",
    specifications: [
      "Professional bubble machines (3 units)",
      "Smoke bubble capability",
      "LED bubble effects",
      "Special bubble solution",
      "Multiple pattern programs",
      "DMX controller included",
      "Trained operator",
      "Indoor/outdoor compatible",
      "Setup time: 1 hour",
    ],
    available: true,
  },
  {
    id: "decor-fx-4",
    name: "Flower Shower System",
    category: "decor",
    subCategory: "Special Effects",
    price: 12000,
    setupCharges: 2000,
    deliveryCharges: 1500,
    rentalDuration: {
      minimum: "2 hours",
      standard: "4 hours",
      pricing: {
        hourly: 3000,
        daily: 15000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description: "Automated flower shower system for special moments.",
    specifications: [
      "4 flower shower units",
      "Fresh flower petals included",
      "Remote controlled operation",
      "Multiple shower patterns",
      "Coverage area: 400 sq ft",
      "Indoor/outdoor compatible",
      "Setup with truss system",
      "Operator included",
      "Setup time: 2 hours",
    ],
    available: true,
  },

  // ARTISTS - MEHENDI & MAKEUP
  {
    id: "artist-mehendi-1",
    name: "Premium Bridal Mehendi",
    category: "artists",
    subCategory: "Mehendi",
    price: 15000,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
      pricing: {
        hourly: 3000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1630779374222-d8fc71997efb?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1604430456280-43f652c497aa?auto=format&fit=crop&q=80",
    ],
    description: "Premium bridal mehendi service with exclusive designs.",
    specifications: [
      "Expert mehendi artist",
      "Premium natural mehendi cones",
      "Exclusive design catalog",
      "Both hands and feet coverage",
      "Arabic and Indian designs",
      "Duration: 3-4 hours",
      "Touch-up service included",
      "Natural darkening tips",
      "Aftercare kit provided",
    ],
    available: true,
  },
  {
    id: "artist-hair-1",
    name: "Professional Hair Styling",
    category: "artists",
    subCategory: "Hair Styling",
    price: 8000,
    deliveryCharges: 500,
    rentalDuration: {
      minimum: "2 hours",
      standard: "3 hours",
      pricing: {
        hourly: 3000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description: "Professional hair styling service for all occasions.",
    specifications: [
      "Expert hair stylist",
      "Premium styling products",
      "Heat protection treatment",
      "Hair accessories included",
      "Multiple style options",
      "Pre-event consultation",
      "Touch-up kit provided",
      "Style duration: 6-8 hours",
      "Extension services available",
    ],
    available: true,
  },

  // SUPPORT STAFF - HOSPITALITY
  {
    id: "staff-hosp-1",
    name: "Welcome Staff Team",
    category: "support-staff",
    subCategory: "Hospitality",
    price: 12000,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
      pricing: {
        hourly: 2000,
        daily: 15000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description: "Professional welcome staff team for events.",
    specifications: [
      "6 trained staff members",
      "Professional uniforms",
      "Guest management expertise",
      "Multi-lingual capabilities",
      "Coordination with event team",
      "Welcome drink service",
      "Guest list management",
      "Emergency handling trained",
      "Backup staff available",
    ],
    available: true,
  },
  {
    id: "staff-security-1",
    name: "Event Security Team",
    category: "support-staff",
    subCategory: "Security",
    price: 10000,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "6 hours",
      standard: "8 hours",
      pricing: {
        hourly: 1500,
        daily: 12000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description: "Professional security team for event safety.",
    specifications: [
      "4 trained security guards",
      "1 supervisor",
      "Professional uniforms",
      "Security equipment",
      "Crowd management trained",
      "Emergency protocols",
      "CCTV monitoring",
      "Parking management",
      "VIP security available",
    ],
    available: true,
  },

  // DECOR - EVENT DECOR
  {
    id: "decor-event-1",
    name: "Haldi Ceremony Setup",
    category: "decor",
    subCategory: "Event Decor",
    price: 25000,
    setupCharges: 3000,
    deliveryCharges: 2000,
    rentalDuration: {
      minimum: "6 hours",
      standard: "8 hours",
      pricing: {
        daily: 25000,
      },
    },
    image: [
      "https://i.postimg.cc/jS81v02C/Snapinsta-app-432075118-1598052097626704-9076143774487201249-n-1080.jpg",
      "https://i.postimg.cc/66RZStdQ/Basic-in-house-Mehndi-backdrop-decor.jpg",
      "https://i.postimg.cc/4y4YgxhQ/def82651-f974-40f3-b528-9f50e0a2207c.jpg",
      "https://i.postimg.cc/44wK1VrL/c8f80ca3-8587-433c-8925-e6f5c16f1123.jpg",
    ],
    description:
      "Complete Haldi ceremony decoration with traditional elements.",
    specifications: [
      "Traditional mandap setup",
      "Floral decoration",
      "Seating arrangement for 50 people",
      "Cushions and low seating",
      "Backdrop decoration",
      "Props for photography",
      "Lighting arrangement",
      "Traditional elements",
      "Setup time: 4 hours",
      "Cleanup included",
    ],
    available: true,
  },
  {
    id: "decor-event-2",
    name: "Reception Stage Package",
    category: "decor",
    subCategory: "Event Decor",
    price: 75000,
    setupCharges: 10000,
    deliveryCharges: 5000,
    rentalDuration: {
      minimum: "12 hours",
      standard: "24 hours",
      pricing: {
        daily: 75000,
      },
    },
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ],
    description: "Premium reception stage and venue decoration package.",
    specifications: [
      "30x20 ft stage setup",
      "Premium backdrop design",
      "LED wall integration",
      "Floral arrangements",
      "Premium furniture set",
      "Walkway decoration",
      "Photo booth area",
      "Complete venue lighting",
      "Setup time: 8 hours",
      "Professional decor team",
    ],
    available: true,
  },

  // Photography Packages
  {
    id: "wedding-full-narrative",
    name: "Comprehensive Wedding Narrative Package",
    category: "photography",
    subCategory: "Wedding",
    price: 150000,
    setupCharges: 10000,
    deliveryCharges: 5000,
    rentalDuration: {
      minimum: "12 hours",
      standard: "Full Wedding Weekend",
    },
    description:
      "A complete package covering all aspects of your wedding, from pre-wedding ceremonies to the reception, ensuring every moment is beautifully captured.",
    specifications: [
      "End-to-End Wedding Documentation",
      "Multi-Event Coverage",
      "Cinematic Storytelling",
      "Pre-Wedding Ceremonies",
      "Haldi",
      "Mehendi",
      "Sangeet",
      "Wedding Ceremony",
      "Reception",
      "Candid Photography",
      "Traditional Photography",
      "Drone Aerial Shots",
      "50-Page Luxury Album",
      "Full-Length Wedding Video",
      "Cinematic Trailer",
      "Social Media Reels",
      "Pre-Wedding Photo Story",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ],
  },
  {
    id: "wedding-ceremony-focus",
    name: "Wedding Ceremony Essence Package",
    category: "photography",
    subCategory: "Wedding",
    price: 100000,
    setupCharges: 8000,
    deliveryCharges: 5000,
    rentalDuration: {
      minimum: "12 hours",
      standard: "Wedding Day Full Coverage",
    },
    description:
      "Focus on capturing the essence of your wedding ceremony with professional storytelling and authentic moment documentation.",
    specifications: [
      "Focused Wedding Ceremony Capture",
      "Professional Storytelling",
      "Authentic Moment Documentation",
      "Candid Photography",
      "Traditional Poses",
      "Drone Cinematography",
      "50-Page Wedding Album",
      "Full-Length Ceremony Video",
      "Emotional Highlight Reel",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ],
  },
  {
    id: "reception-elegance-package",
    name: "Reception Elegance Photography",
    category: "photography",
    subCategory: "Reception",
    price: 50000,
    setupCharges: 3000,
    deliveryCharges: 2000,
    rentalDuration: {
      minimum: "6 hours",
      standard: "8 hours",
    },
    description:
      "Capture the glamour and elegance of your wedding reception with sophisticated styling and emotional storytelling.",
    specifications: [
      "Glamorous Reception Moments",
      "Sophisticated Styling",
      "Emotional Storytelling",
      "Traditional Photography",
      "Candid Captures",
      "30-Page Luxury Album",
      "Full-Length Reception Video",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ],
  },
  {
    id: "pre-wedding-cinematic",
    name: "Cinematic Pre-Wedding Experience",
    category: "photography",
    subCategory: "Pre Wedding",
    price: 40000,
    setupCharges: 2000,
    deliveryCharges: 1500,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
    },
    description:
      "A cinematic approach to capturing your love story before the wedding, with artistic location shoots and personalized narratives.",
    specifications: [
      "Romantic Storytelling",
      "Artistic Location Shoots",
      "Personalized Narrative",
      "Cinematic Photoshoot",
      "Artistic Edited Photos",
      "Cinematic Pre-Wedding Film",
      "Social Media Teasers",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ],
  },
  {
    id: "engagement-love-story",
    name: "Engagement Love Story Package",
    category: "photography",
    subCategory: "Engagement",
    price: 30000,
    setupCharges: 2000,
    deliveryCharges: 1500,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
    },
    description:
      "Capture the intimate moments of your engagement with storytelling photography and cinematic invitation videos.",
    specifications: [
      "Intimate Moment Capturing",
      "Storytelling Photography",
      "Cinematic Invitation Video",
      "Candid Engagement Shots",
      "Traditional Portraits",
      "Edited Photo Collection",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ],
  },
  {
    id: "birthday-memory-maker",
    name: "Birthday Celebration Photography",
    category: "photography",
    subCategory: "Birthdays",
    price: 25000,
    setupCharges: 1500,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
    },
    description:
      "Capture the joy and energy of birthday celebrations with candid and cinematic photography.",
    specifications: [
      "Joyful Moment Capturing",
      "Energetic Event Coverage",
      "Emotional Storytelling",
      "Candid Birthday Shots",
      "Traditional Group Photos",
      "20-Page Album",
      "Cinematic Birthday Video",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ],
  },
  {
    id: "pr-event-narrative",
    name: "PR Events Professional Coverage",
    category: "photography",
    subCategory: "PR Events",
    price: 60000,
    setupCharges: 3000,
    deliveryCharges: 2000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
    },
    description:
      "Professional coverage for PR events, ensuring brand storytelling and media-ready content.",
    specifications: [
      "Professional Event Documentation",
      "Brand Storytelling",
      "Media-Ready Content",
      "Candid Corporate Shots",
      "Drone Event Coverage",
      "Edited Professional Images",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ],
  },
  {
    id: "product-visual-storytelling",
    name: "Product Photography Essentials",
    category: "photography",
    subCategory: "Products Photography",
    price: 20000,
    setupCharges: 1000,
    deliveryCharges: 500,
    rentalDuration: {
      minimum: "2 hours",
      standard: "4 hours",
    },
    description:
      "Creative photography services to showcase your products with professional styling and marketable visual content.",
    specifications: [
      "Creative Product Showcase",
      "Professional Styling",
      "Marketable Visual Content",
      "Creative Product Shots",
      "Studio and Lifestyle Images",
      "Multiple Angle Captures",
      "Product Showcase Video",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ],
  },
  {
    id: "private-moments-collection",
    name: "Private Events Intimate Photography",
    category: "photography",
    subCategory: "Private Events",
    price: 30000,
    setupCharges: 2000,
    deliveryCharges: 1500,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
    },
    description:
      "Capture the essence of private events with intimate photography that preserves cultural ceremonies and personal milestones.",
    specifications: [
      "Cultural Ceremony Documentation",
      "Emotional Moment Capturing",
      "Personal Milestone Preservation",
      "Traditional Ceremony Shots",
      "Candid Family Moments",
      "Cultural Detail Captures",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ],
  },
  // Lighting Products
  {
    id: "lighting-house-weddings",
    name: "House Lighting - Weddings",
    category: "lighting",
    subCategory: "Weddings",
    price: 20000,
    setupCharges: 3000,
    deliveryCharges: 1500,
    rentalDuration: {
      minimum: "4 hours",
      standard: "8 hours",
      pricing: {
        hourly: 5000,
        daily: 20000,
      },
    },
    description:
      "Elegant lighting solutions for weddings, creating a romantic and festive atmosphere.",
    specifications: [
      "LED string lights",
      "Spotlights for key areas",
      "Color-changing options",
      "Setup for indoor and outdoor",
      "Professional installation included",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ], // Replace with actual image URL
  },
  {
    id: "lighting-festive",
    name: "Festive Lighting",
    category: "lighting",
    subCategory: "Festive",
    price: 15000,
    setupCharges: 2000,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "8 hours",
      pricing: {
        hourly: 4000,
        daily: 15000,
      },
    },
    description:
      "Vibrant lighting solutions for festive occasions, enhancing the celebratory mood.",
    specifications: [
      "Colorful LED lights",
      "Decorative lanterns",
      "String lights for outdoor use",
      "Setup for various festive themes",
      "Professional installation included",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ], // Replace with actual image URL
  },
  {
    id: "lighting-personal-events",
    name: "Personal Events Lighting",
    category: "lighting",
    subCategory: "Personal Events",
    price: 18000,
    setupCharges: 2500,
    deliveryCharges: 1200,
    rentalDuration: {
      minimum: "4 hours",
      standard: "8 hours",
      pricing: {
        hourly: 4500,
        daily: 18000,
      },
    },
    description:
      "Customized lighting solutions for personal events, tailored to your needs.",
    specifications: [
      "LED uplighting",
      "Mood lighting options",
      "Thematic decorations",
      "Setup for indoor and outdoor",
      "Professional installation included",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ], // Replace with actual image URL
  },
  {
    id: "lighting-event-venue",
    name: "Event Venue Lighting",
    category: "lighting",
    subCategory: "Event Venue",
    price: 25000,
    setupCharges: 4000,
    deliveryCharges: 2000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "8 hours",
      pricing: {
        hourly: 6000,
        daily: 25000,
      },
    },
    description:
      "Comprehensive lighting solutions for event venues, ensuring a captivating ambiance.",
    specifications: [
      "Stage lighting",
      "Ambient lighting",
      "Spotlights for key areas",
      "Customizable lighting setups",
      "Professional installation included",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ], // Replace with actual image URL
  },
  {
    id: "lighting-shops-businesses",
    name: "Shops/Businesses Lighting",
    category: "lighting",
    subCategory: "Shops/Businesses",
    price: 22000,
    setupCharges: 3500,
    deliveryCharges: 1500,
    rentalDuration: {
      minimum: "4 hours",
      standard: "8 hours",
      pricing: {
        hourly: 5500,
        daily: 22000,
      },
    },
    description:
      "Professional lighting solutions for shops and businesses, enhancing visibility and appeal.",
    specifications: [
      "LED display lighting",
      "Track lighting for products",
      "Energy-efficient options",
      "Setup for indoor and outdoor",
      "Professional installation included",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ], // Replace with actual image URL
  },
  {
    id: "lighting-temple-pandals",
    name: "Temple/Pandals Lighting",
    category: "lighting",
    subCategory: "Temple/Pandals",
    price: 20000,
    setupCharges: 3000,
    deliveryCharges: 1500,
    rentalDuration: {
      minimum: "4 hours",
      standard: "8 hours",
      pricing: {
        hourly: 5000,
        daily: 20000,
      },
    },
    description:
      "Specialized lighting solutions for temples and pandals, creating a divine atmosphere.",
    specifications: [
      "Traditional decorative lights",
      "LED lights for vibrant displays",
      "Setup for religious events",
      "Professional installation included",
      "Customizable lighting themes",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ], // Replace with actual image URL
  },
  // Decor Products
  {
    id: "decor-wedding",
    name: "Wedding Decor",
    category: "decor",
    subCategory: "Wedding",
    price: 50000,
    setupCharges: 10000,
    deliveryCharges: 5000,
    rentalDuration: {
      minimum: "12 hours",
      standard: "Full Wedding Day",
    },
    description:
      "Complete wedding decoration package with elegant themes and setups.",
    specifications: [
      "Floral arrangements",
      "Stage setup",
      "Lighting decorations",
      "Seating arrangements",
      "Thematic decor elements",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ], // Replace with actual image URL
  },
  {
    id: "decor-engagement",
    name: "Engagement Decor",
    category: "decor",
    subCategory: "Engagement",
    price: 30000,
    setupCharges: 5000,
    deliveryCharges: 2000,
    rentalDuration: {
      minimum: "6 hours",
      standard: "Engagement Day",
    },
    description: "Beautifully designed decor for engagement ceremonies.",
    specifications: [
      "Floral backdrops",
      "Seating arrangements",
      "Lighting setups",
      "Thematic decor elements",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ], // Replace with actual image URL
  },
  {
    id: "decor-haldi",
    name: "Haldi / Mangalasnanam Decor",
    category: "decor",
    subCategory: "Haldi",
    price: 20000,
    setupCharges: 3000,
    deliveryCharges: 1500,
    rentalDuration: {
      minimum: "4 hours",
      standard: "Haldi Ceremony",
    },
    description: "Traditional decor for Haldi or Mangalasnanam ceremonies.",
    specifications: [
      "Colorful floral arrangements",
      "Traditional seating",
      "Decorative elements",
      "Lighting arrangements",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ], // Replace with actual image URL
  },
  {
    id: "decor-mehendi",
    name: "Mehendi Decor",
    category: "decor",
    subCategory: "Mehendi",
    price: 25000,
    setupCharges: 4000,
    deliveryCharges: 2000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "Mehendi Ceremony",
    },
    description: "Vibrant decor for Mehendi ceremonies with artistic elements.",
    specifications: [
      "Colorful drapes",
      "Seating arrangements",
      "Floral decorations",
      "Lighting setups",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ], // Replace with actual image URL
  },
  {
    id: "decor-reception",
    name: "Reception Decor",
    category: "decor",
    subCategory: "Reception",
    price: 60000,
    setupCharges: 12000,
    deliveryCharges: 6000,
    rentalDuration: {
      minimum: "12 hours",
      standard: "Reception Day",
    },
    description: "Elegant decor for wedding receptions with luxurious themes.",
    specifications: [
      "Stage setup",
      "Floral arrangements",
      "Lighting decorations",
      "Seating arrangements",
      "Thematic decor elements",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ], // Replace with actual image URL
  },
  {
    id: "decor-birthday-themed",
    name: "Birthday Decor - Themed Base",
    category: "decor",
    subCategory: "Birthday",
    price: 15000,
    setupCharges: 2000,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "Birthday Party",
    },
    description:
      "Themed decor for birthday celebrations, tailored to your theme.",
    specifications: [
      "Thematic decorations",
      "Balloons and banners",
      "Seating arrangements",
      "Lighting setups",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ], // Replace with actual image URL
  },
  {
    id: "decor-birthday-generic",
    name: "Birthday Decor - Generic",
    category: "decor",
    subCategory: "Birthday",
    price: 10000,
    setupCharges: 1500,
    deliveryCharges: 800,
    rentalDuration: {
      minimum: "4 hours",
      standard: "Birthday Party",
    },
    description:
      "Generic decor for birthday celebrations, suitable for all ages.",
    specifications: [
      "Colorful decorations",
      "Balloons and streamers",
      "Seating arrangements",
      "Lighting setups",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ], // Replace with actual image URL
  },
  {
    id: "decor-anniversary",
    name: "Anniversary Decor",
    category: "decor",
    subCategory: "Anniversary",
    price: 40000,
    setupCharges: 8000,
    deliveryCharges: 4000,
    rentalDuration: {
      minimum: "6 hours",
      standard: "Anniversary Celebration",
    },
    description:
      "Elegant decor for anniversary celebrations with romantic themes.",
    specifications: [
      "Floral arrangements",
      "Candlelight setups",
      "Seating arrangements",
      "Lighting decorations",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ], // Replace with actual image URL
  },
  {
    id: "decor-sangeeth",
    name: "Sangeeth Decor",
    category: "decor",
    subCategory: "Sangeeth",
    price: 35000,
    setupCharges: 7000,
    deliveryCharges: 3000,
    rentalDuration: {
      minimum: "6 hours",
      standard: "Sangeeth Night",
    },
    description: "Vibrant decor for Sangeeth ceremonies with musical themes.",
    specifications: [
      "Colorful drapes",
      "Stage setup",
      "Lighting arrangements",
      "Seating arrangements",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ], // Replace with actual image URL
  },
  {
    id: "decor-house-warming",
    name: "House Warming Decor",
    category: "decor",
    subCategory: "House Warming",
    price: 25000,
    setupCharges: 5000,
    deliveryCharges: 2000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "House Warming Ceremony",
    },
    description: "Traditional decor for house warming ceremonies.",
    specifications: [
      "Floral arrangements",
      "Traditional seating",
      "Decorative elements",
      "Lighting arrangements",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ], // Replace with actual image URL
  },
  {
    id: "decor-cradle-ceremony",
    name: "Cradle Ceremony Decor",
    category: "decor",
    subCategory: "Cradle Ceremony",
    price: 20000,
    setupCharges: 4000,
    deliveryCharges: 1500,
    rentalDuration: {
      minimum: "4 hours",
      standard: "Cradle Ceremony",
    },
    description: "Beautifully designed decor for cradle ceremonies.",
    specifications: [
      "Floral backdrops",
      "Seating arrangements",
      "Lighting setups",
      "Thematic decor elements",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ], // Replace with actual image URL
  },
  {
    id: "decor-pooja",
    name: "Pooja Decor",
    category: "decor",
    subCategory: "Pooja",
    price: 15000,
    setupCharges: 3000,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "Pooja Ceremony",
    },
    description:
      "Traditional decor for Pooja ceremonies, creating a serene atmosphere.",
    specifications: [
      "Floral arrangements",
      "Traditional seating",
      "Decorative elements",
      "Lighting arrangements",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ], // Replace with actual image URL
  },
  // Sound Products
  {
    id: "sound-package-1",
    name: "Sound and Lighting Package 1",
    category: "sound",
    subCategory: "50 People",
    price: 15000,
    setupCharges: 2000,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "8 hours",
    },
    image: [
      "https://example.com/image/sound-package-1-1.jpg", // Replace with actual image URLs
      "https://example.com/image/sound-package-1-2.jpg",
    ],
    description: "Sound and lighting package suitable for up to 50 people.",
    specifications: [
      "2 PA speakers with Amp and mics",
      "4 Par cans",
      "2 Sharpies (Optional)",
    ],
    available: true,
  },
  {
    id: "sound-package-2",
    name: "Sound and Lighting Package 2",
    category: "sound",
    subCategory: "100 People - Indoor",
    price: 30000,
    setupCharges: 4000,
    deliveryCharges: 2000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "8 hours",
    },
    image: [
      "https://example.com/image/sound-package-2-1.jpg", // Replace with actual image URLs
      "https://example.com/image/sound-package-2-2.jpg",
    ],
    description:
      "Comprehensive sound and lighting package for indoor events up to 100 people.",
    specifications: [
      "Double bin setup with 2 Sub woofers and 4 Tops",
      "Required amplifier and console",
      "Option for choosing DJ according to genre",
      "4 Par Cans",
      "2 Sharpies",
      "Smoke Machine",
      "Laser machine",
      "Optional Dance Floor",
      "Additional items can be accommodated based on request",
    ],
    available: true,
  },
  {
    id: "sound-package-3",
    name: "Sound and Lighting Package 3",
    category: "sound",
    subCategory: "200-500 People - Indoor",
    price: 60000,
    setupCharges: 8000,
    deliveryCharges: 3000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "8 hours",
    },
    image: [
      "https://example.com/image/sound-package-3-1.jpg", // Replace with actual image URLs
      "https://example.com/image/sound-package-3-2.jpg",
    ],
    description:
      "Advanced sound and lighting package for larger indoor events (200-500 people).",
    specifications: [
      "Double Bin setup with 4 Subs and 8 Tops",
      "Required amplifiers and console",
      "2 Speaker Monitors",
      "4 Mics",
      "Truss - 20x40 ft",
      "40-50 Par cans",
      "8-10 Sharpies",
      "4 Co2 Smoke Jets",
      "8 Electric Sparkle Machines",
      "4 Flame Machines",
      "Optional Live Band Setup",
      "Optional Stage with black mat",
      "Optional LED Screens",
      "Additional items can be accommodated",
    ],
    available: true,
  },
  {
    id: "sound-package-4",
    name: "Sound and Lighting Package 4",
    category: "sound",
    subCategory: "100 People - Outdoor",
    price: 50000,
    setupCharges: 7000,
    deliveryCharges: 2500,
    rentalDuration: {
      minimum: "4 hours",
      standard: "8 hours",
    },
    image: [
      "https://example.com/image/sound-package-4-1.jpg", // Replace with actual image URLs
      "https://example.com/image/sound-package-4-2.jpg",
    ],
    description:
      "Outdoor sound and lighting package for events up to 100 people.",
    specifications: [
      "Double Bin Setup with 4 Subs and 8 Tops",
      "Required amplifier and console",
      "2 Speaker Monitors",
      "8 Par cans",
      "2 Sharpies",
      "Smoke machine",
      "8x8 ft LED screen",
      "Optional Dance Floor",
      "Optional Live band setup",
      "Additional Lightings and speakers",
    ],
    available: true,
  },
  {
    id: "sound-package-5",
    name: "Sound and Lighting Package 5",
    category: "sound",
    subCategory: "200 People - Sangeeth",
    price: 55000,
    setupCharges: 6000,
    deliveryCharges: 2500,
    rentalDuration: {
      minimum: "4 hours",
      standard: "8 hours",
    },
    image: [
      "https://example.com/image/sound-package-5-1.jpg", // Replace with actual image URLs
      "https://example.com/image/sound-package-5-2.jpg",
    ],
    description:
      "Specialized sound and lighting package for Sangeeth events for up to 200 people.",
    specifications: [
      "Double Bin Setup with 4 Subs and 8 Tops",
      "Required amplifier and console",
      "2 Speaker monitors",
      "2 Mics",
      "8 Par cans",
      "Additional items can be accommodated based on request",
    ],
    available: true,
  },
];
