import { base } from "framer-motion/client";
import { Product } from "./types";

const baseUrl = "https://myutsav.s3.ap-south-1.amazonaws.com";

export const PRODUCTS: Product[] = [
  // Decor Products
  {
    id: "decor-wedding",
    idealFor: ["Weddings"],
    name: "Wedding Decor",
    category: "decor",
    subCategory: "Wedding",
    price: 99999,
    setupCharges: 10000,
    deliveryCharges: 5000,
    rentalDuration: {
      minimum: "12 hours",
      standard: "Full Wedding Day",
    },
    description:
      "Complete wedding decoration package with elegant themes and setups, tailored to create a memorable atmosphere for your special day.",
    specifications: [
      "Floral arrangements",
      "Stage setup",
      "Lighting decorations",
      "Seating arrangements on stage",
      "Thematic decor elements",
      "Table centerpieces",
      "Backdrop designs",
      "Setup and travel charges included",
      "Additional items can be accommodated upon request",
    ],
    available: true,
    image: [
      `${baseUrl}/Wedding-image-4.jpg`,
      `${baseUrl}/Wedding-image-2.jpg`,
      `${baseUrl}/Wedding-image-3.jpg`,
      `${baseUrl}/Wedding-image-1.jpg`,
    ], // Replace with actual image URL
  },
  {
    id: "decor-engagement",
    idealFor: ["Engagement"],
    name: "Engagement Decor",
    category: "decor",
    subCategory: "Engagement",
    price: 34999,
    setupCharges: 5000,
    deliveryCharges: 2000,
    rentalDuration: {
      minimum: "6 hours",
      standard: "Engagement Day",
    },
    description: "Beautifully designed decor for engagement ceremonies.",
    specifications: [
      "Floral backdrops",
      "Seating arrangements for couple",
      "Lighting setups",
      "Thematic decor elements",
      "Setup and travel charges included",
      "Additional items can be accommodated upon request",
    ],
    available: true,
    image: [
      `${baseUrl}/Engagement-image-2.jpg`,
      `${baseUrl}/Engagement-image-1.jpg`,
      `${baseUrl}/Engagement-image-3.jpg`,
      `${baseUrl}/Reception-image-1.jpg`,
      `${baseUrl}/Reception-image-2.jpg`,
      `${baseUrl}/Reception-image-3.jpg`,
      `${baseUrl}/Engagement-image-4.jpg`,
    ], // Replace with actual image URL
  },
  {
    id: "decor-haldi-1",
    idealFor: ["Haldi"],
    name: "Haldi Ceremony Setup",
    category: "decor",
    subCategory: "Event Decor",
    price: 25000,
    setupCharges: 3000,
    deliveryCharges: 2000,
    rentalDuration: {
      minimum: "6 hours",
      standard: "8 hours",
      pricing: {
        daily: 25000,
      },
    },
    image: [
      `${baseUrl}/Haldi-image-6.jpg`,
      `${baseUrl}/Haldi-image-1.jpg`,
      `${baseUrl}/Haldi-image-2.jpg`,
      `${baseUrl}/Haldi-image-3.jpg`,
      `${baseUrl}/Haldi-image-4.jpg`,
      `${baseUrl}/Haldi-image-5.jpg`,
    ],
    description:
      "Complete Haldi ceremony decoration with traditional elements.",
    specifications: [
      "Traditional mandap setup",
      "Floral decoration",
      "Seating arrangement for 50 people",
      "Cushions and low seating",
      "Backdrop decoration",
      "Props for photography",
      "Lighting arrangement",
      "Traditional elements",
      "Setup time: 4 hours",
      "Cleanup included",
    ],
    available: true,
  },
  {
    id: "decor-mehendi",
    idealFor: ["Mehendi"],
    name: "Mehendi Decor",
    category: "decor",
    subCategory: "Mehendi",
    price: 19999,
    setupCharges: 4000,
    deliveryCharges: 2000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "Mehendi Ceremony",
    },
    description: "Vibrant decor for Mehendi ceremonies with artistic elements.",
    specifications: [
      "Colorful drapes",
      "Seating arrangements",
      "Floral decorations",
      "Lighting setups",
      "Cusions as per theme",
      "Setup and travel charges included",
      "Additional items can be accommodated upon request",
    ],
    available: true,
    image: [
      `${baseUrl}/Mehendi-decor-2.jpg`,
      `${baseUrl}/Mehendi-decor-3.jpg`,
      `${baseUrl}/Mehendi-decor-4.jpg`,
      `${baseUrl}/Mehendi-decor-1.jpg`,
    ], // Replace with actual image URL
  },
  {
    id: "decor-reception",
    idealFor: ["Reception"],
    name: "Reception Decor",
    category: "decor",
    subCategory: "Reception",
    price: 60000,
    setupCharges: 12000,
    deliveryCharges: 6000,
    rentalDuration: {
      minimum: "12 hours",
      standard: "Reception Day",
    },
    description: "Elegant decor for wedding receptions with luxurious themes.",
    specifications: [
      "Stage setup",
      "Floral arrangements",
      "Lighting decorations",
      "Seating arrangements",
      "Thematic decor elements",
    ],
    available: true,
    image: [
      `${baseUrl}/Reception-image-4.jpg`,
      `${baseUrl}/Reception-image-1.jpg`,
      `${baseUrl}/Reception-image-2.jpg`,
      `${baseUrl}/Reception-image-3.jpg`,
      `${baseUrl}/Engagement-image-2.jpg`,
      `${baseUrl}/Engagement-image-1.jpg`,
      `${baseUrl}/Engagement-image-3.jpg`,
      `${baseUrl}/Engagement-image-4.jpg`,
    ], // Replace with actual image URL
  },
  {
    id: "decor-birthday-themed",
    idealFor: ["Birthdays"],
    name: "Birthday Decor - Themed Base",
    category: "decor",
    subCategory: "Birthday",
    price: 15000,
    setupCharges: 2000,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "Birthday Party",
    },
    description:
      "Themed decor for birthday celebrations, tailored to your theme.",
    specifications: [
      "Thematic decorations",
      "Balloons and banners",
      "Seating arrangements",
      "Lighting setups",
    ],
    available: true,
    image: [
      `${baseUrl}/Birthday-decor-image-1.jpg`,
      `${baseUrl}/Birthday-decor-image-2.jpg`,
      `${baseUrl}/Birthday-decor-image-3.jpg`,
      `${baseUrl}/Birthday-decor-image-4.jpg`,
    ], // Replace with actual image URL
  },
  {
    id: "decor-birthday-generic",
    idealFor: ["Birthdays"],
    name: "Birthday Decor - Generic",
    category: "decor",
    subCategory: "Birthday",
    price: 10000,
    setupCharges: 1500,
    deliveryCharges: 800,
    rentalDuration: {
      minimum: "4 hours",
      standard: "Birthday Party",
    },
    description:
      "Generic decor for birthday celebrations, suitable for all ages.",
    specifications: [
      "Colorful decorations",
      "Balloons and streamers",
      "Seating arrangements",
      "Lighting setups",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ], // Replace with actual image URL
  },
  {
    id: "decor-anniversary",
    idealFor: ["Anniversary"],
    name: "Anniversary Decor",
    category: "decor",
    subCategory: "Anniversary",
    price: 40000,
    setupCharges: 8000,
    deliveryCharges: 4000,
    rentalDuration: {
      minimum: "6 hours",
      standard: "Anniversary Celebration",
    },
    description:
      "Elegant decor for anniversary celebrations with romantic themes.",
    specifications: [
      "Floral arrangements",
      "Candlelight setups",
      "Seating arrangements",
      "Lighting decorations",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ], // Replace with actual image URL
  },
  {
    id: "decor-sangeeth",
    idealFor: ["Sangeeth"],
    name: "Sangeeth Decor",
    category: "decor",
    subCategory: "Sangeeth",
    price: 35000,
    setupCharges: 7000,
    deliveryCharges: 3000,
    rentalDuration: {
      minimum: "6 hours",
      standard: "Sangeeth Night",
    },
    description: "Vibrant decor for Sangeeth ceremonies with musical themes.",
    specifications: [
      "Colorful drapes",
      "Stage setup",
      "Lighting arrangements",
      "Seating arrangements",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ], // Replace with actual image URL
  },
  {
    id: "decor-house-warming",
    idealFor: ["House Warming"],
    name: "House Warming Decor",
    category: "decor",
    subCategory: "House Warming",
    price: 9999,
    setupCharges: 5000,
    deliveryCharges: 2000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "House Warming Ceremony",
    },
    description: "Traditional decor for house warming ceremonies.",
    specifications: [
      "Traditional decorations",
      "Floral arrangements",
      "Decorative elements",
      "Lighting arrangements as per needed",
      "Customization available upon request",
    ],
    available: true,
    image: [
      `${baseUrl}/House-warming-decor-image-1.jpg`,
      `${baseUrl}/House-warming-decor-image-2.jpg`,
      `${baseUrl}/House-warming-decor-image-3.jpg`,
      `${baseUrl}/House-warming-decor-image-4.jpg`,
      `${baseUrl}/House-warming-decor-image-5.jpg`,
      `${baseUrl}/House-warming-decor-image-6.jpg`,
    ], // Replace with actual image URL
  },
  {
    id: "decor-cradle-ceremony",
    idealFor: ["Birthdays"],
    name: "Cradle Ceremony Decor",
    category: "decor",
    subCategory: "Cradle Ceremony",
    price: 20000,
    setupCharges: 4000,
    deliveryCharges: 1500,
    rentalDuration: {
      minimum: "4 hours",
      standard: "Cradle Ceremony",
    },
    description: "Beautifully designed decor for cradle ceremonies.",
    specifications: [
      "Floral backdrops",
      "Seating arrangements",
      "Lighting setups",
      "Thematic decor elements",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ], // Replace with actual image URL
  },
  {
    id: "decor-pooja",
    idealFor: ["Pooja", "Festivals"],
    name: "Pooja Decor",
    category: "decor",
    subCategory: "Pooja",
    price: 15000,
    setupCharges: 3000,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "Pooja Ceremony",
    },
    description:
      "Traditional decor for Pooja ceremonies, creating a serene atmosphere.",
    specifications: [
      "Floral arrangements",
      "Traditional seating",
      "Decorative elements",
      "Lighting arrangements",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ], // Replace with actual image URL
  },
  // Sound Products
  {
    id: "sound-package-1",
    idealFor: ["Birthdays", "Private Parties", "Anniversary", "Engagement"],
    name: "Premium Sound & Lighting Package for Small Events",
    category: "sound",
    subCategory: "50 People",
    price: 5499,
    setupCharges: 2000,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "8 hours",
    },
    image: [
      "https://example.com/image/sound-package-1-1.jpg", // Replace with actual image URLs
      "https://example.com/image/sound-package-1-2.jpg",
    ],
    description:
      "This premium sound and lighting package is designed for intimate gatherings of up to 50 guests, perfect for parties, corporate events, and small celebrations.",
    specifications: [
      "2 Professional PA Speakers with Amplifier and Microphones",
      "4 LED Par Can Lights",
      "2 Sharpie Markers (Optional)",
      "1 Wireless Microphone",
      "1 Backup Wireless Microphone",
      "Includes Setup and Travel Costs",
      "Standard Service duration available for up to 6 hours",
    ],
    available: true,
  },
  {
    id: "sound-package-2",
    idealFor: [""],
    name: "Premium Sound and Lighting Package for Medium-Sized Events",
    category: "sound",
    subCategory: "100 People - Indoor",
    price: 24999,
    setupCharges: 4000,
    deliveryCharges: 2000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "8 hours",
    },
    image: [
      "https://example.com/image/sound-package-2-1.jpg", // Replace with actual image URLs
      "https://example.com/image/sound-package-2-2.jpg",
    ],
    description:
      "A comprehensive sound and lighting solution designed for indoor events accommodating up to 100 guests, ensuring an unforgettable experience.",
    specifications: [
      "Dual bin setup featuring 2 Subwoofers and 4 Top Speakers",
      "Includes necessary amplifier and mixing console",
      "DJ selection available based on music genre preference",
      "4 Par Cans for enhanced lighting effects",
      "2 Sharpies for focused lighting",
      "Smoke Machine for atmospheric effects",
      "Laser Machine for dynamic visuals",
      "Optional Dance Floor available",
      "Standard Service duration available for up to 6 hours",
      "Additional equipment can be accommodated upon request",
    ],
    available: true,
  },
  {
    id: "sound-package-3",
    idealFor: ["Fests", "Sangeeth", "Reception", "Others"],
    name: "Elite Sound and Lighting Package",
    category: "sound",
    subCategory: "200-500 People - Indoor",
    price: 74999,
    setupCharges: 8000,

    deliveryCharges: 3000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "8 hours",
    },
    image: [
      "https://example.com/image/sound-package-3-1.jpg", // Replace with actual image URLs
      "https://example.com/image/sound-package-3-2.jpg",
    ],
    description:
      "An advanced sound and lighting solution tailored for larger indoor events accommodating 200 to 500 guests, ensuring a spectacular experience.",
    specifications: [
      "Double bin setup featuring 4 Subwoofers and 8 Top Speakers",
      "Includes necessary amplifiers and mixing console",
      "2 Speaker Monitors for optimal sound distribution",
      "4 Microphones for clear audio capture",
      "Truss dimensions: 20x40 ft for structural support",
      "40-50 Par Cans for extensive lighting coverage",
      "8-10 Sharpies for focused lighting effects",
      "4 CO2 Smoke Jets for dramatic effects",
      "8 Electric Sparkle Machines for visual excitement",
      "4 Flame Machines for stunning visuals",
      "Optional Live Band Setup for enhanced entertainment",
      "Optional Stage with black mat for a professional look",
      "Optional LED Screens for visual presentations",
      "Additional items can be accommodated upon request",
      "Service duration available for up to 6 hours",
    ],
    available: true,
  },
  {
    id: "sound-package-4",
    idealFor: ["Sangeeth"],
    name: "Sound and Lighting Package 4",
    category: "sound",
    subCategory: "100 People - Outdoor",
    price: 50000,
    setupCharges: 7000,
    deliveryCharges: 2500,
    rentalDuration: {
      minimum: "4 hours",
      standard: "8 hours",
    },
    image: [
      "https://example.com/image/sound-package-4-1.jpg", // Replace with actual image URLs
      "https://example.com/image/sound-package-4-2.jpg",
    ],
    description:
      "Outdoor sound and lighting package for events up to 100 people.",
    specifications: [
      "Double Bin Setup with 4 Subs and 8 Top speakers",
      "Required amplifier and console",
      "2 Speaker Monitors",
      "8 Par cans for lighting",
      "2 Sharpies for focused lighting",
      "Smoke machine for effects",
      "8x8 ft LED screen for visuals",
      "Optional Dance Floor for events",
      "Optional Live band setup for entertainment",
      "Additional lightings and speakers available",
      "Service duration available for up to 6 hours",
    ],
    available: true,
  },
  {
    id: "sound-package-5",
    idealFor: ["Sangeeth", "Fests", "Corporate Events", "Others"],
    name: "Grand Sound and Lighting Package for Large Outdoor Events",
    category: "sound",
    subCategory: "500 People - Outdoor",
    price: 149999,
    setupCharges: 10000,
    deliveryCharges: 5000,
    rentalDuration: {
      minimum: "6 hours",
      standard: "12 hours",
    },
    image: [
      "https://example.com/image/sound-package-5-1.jpg", // Replace with actual image URLs
      "https://example.com/image/sound-package-5-2.jpg",
    ],
    description:
      "An extensive sound and lighting package tailored for large outdoor events, accommodating up to 500 guests, ensuring a spectacular experience.",
    specifications: [
      "Quad bin setup with 8 Subwoofers and 16 Top Speakers",
      "High-powered amplifiers and professional mixing console",
      "Multiple DJ options available based on genre",
      "10 Par Cans and 4 Moving Head Lights for dynamic lighting",
      "4 Speaker Monitors for clear sound distribution",
      "Truss dimensions: 20x40 ft for structural support",
      "Fog and Laser Machines for enhanced effects",
      "Optional Stage Setup with backdrop",
      "Optional LED Video Wall for visuals",
      "Standard Service duration available for up to 12 hours",
      "Additional equipment can be accommodated upon request",
    ],
    available: true,
  },
  // SOUND CATEGORY - DJ SETUPS
  {
    id: "sound-dj-1",
    idealFor: [
      "Weddings",
      "Reception",
      "Birthdays",
      "Small parties",
      "Anniversary",
      "Private Parties",
    ],
    name: "DJ Setup Single Bin",
    category: "sound",
    subCategory: "DJ's Setup",
    price: 11999,
    setupCharges: 2000,
    deliveryCharges: 1500,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
      pricing: {
        hourly: 3000,
        daily: 20000,
      },
    },
    image: [
      "https://image.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description:
      "Elevate your event with our DJ Setup Single Bin, ideal for gatherings of up to 200 people. (Sound varies for indoor and outdoor venues.)",
    specifications: [
      "Standard Service duration available for up to 6 hours",
      "Setup and travel charges included",
      "2 top speakers with stands for optimal sound distribution",
      "2 subwoofers for deep bass",
      "Professional DJ console with advanced features",
      "On-site DJ for live mixing",
      "Basic LED lighting setup to enhance the atmosphere",
      "All necessary cables and connections included",
      "Optional Backup power solutions for uninterrupted fun can be accommodated",
    ],
    available: true,
  },
  {
    id: "sound-dj-2",
    idealFor: [""],
    name: "DJ Setup Double Bin",
    category: "sound",
    subCategory: "DJ's Setup",
    price: 18999,
    setupCharges: 3000,
    deliveryCharges: 2000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
      pricing: {
        hourly: 4500,
        daily: 30000,
      },
    },
    image: [
      "https://myutsav.s3.ap-south-1.amazonaws.com/double-bin-sound-system-rental-500x500.webp",
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description:
      "Unleash the party with our DJ Setup Double Bin, designed for large events and weddings, ensuring an electrifying experience for up to 500 guests. (Sound varies for indoor and outdoor venues.)",
    specifications: [
      "Standard Service duration available for up to 6 hours",
      "Setup and travel charges included",
      "4 top speakers with stands for expansive sound coverage",
      "4 subwoofers for heart-thumping bass",
      "Professional DJ console with effects for creative mixing",
      "Advanced LED lighting system to dazzle your guests",
      "Wireless microphones (2) for seamless announcements",
      "Complete cable management for a tidy setup",
      "Optional Backup equipment included for peace of mind",
    ],
    available: true,
  },

  // Photography Packages
  {
    id: "wedding-full-narrative",
    idealFor: [
      "Weddings",
      "Haldi",
      "Mehendi",
      "Sangeeth",
      "Reception",
      "Engagement",
    ],
    name: "Comprehensive Wedding Narrative Package",
    category: "photography",
    subCategory: "Wedding",
    price: 250000,
    setupCharges: 10000,
    deliveryCharges: 5000,
    rentalDuration: {
      minimum: "12 hours",
      standard: "Full Wedding Weekend",
    },
    description:
      "A complete package covering all aspects of your wedding, from pre-wedding ceremonies to the reception, ensuring every moment is beautifully captured.",
    specifications: [
      "End-to-End Wedding Documentation",
      "Multi-Event Coverage",
      "Cinematic Storytelling",
      "Pre-Wedding Ceremonies",
      "Haldi",
      "Mehendi",
      "Sangeet",
      "Wedding Ceremony",
      "Reception",
      "Candid Photography",
      "Traditional Photography",
      "Drone Aerial Shots",
      "50-Page Luxury Album",
      "Full-Length Wedding Video",
      "Cinematic Trailer",
      "Social Media Reels",
      "Pre-Wedding Photo Story",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ],
  },
  {
    id: "wedding-ceremony-focus",
    idealFor: ["Weddings"],
    name: "Wedding Ceremony Essence Package",
    category: "photography",
    subCategory: "Wedding",
    price: 100000,
    setupCharges: 8000,
    deliveryCharges: 5000,
    rentalDuration: {
      minimum: "12 hours",
      standard: "Wedding Day Full Coverage",
    },
    description:
      "Focus on capturing the essence of your wedding ceremony with professional storytelling and authentic moment documentation.",
    specifications: [
      "Focused Wedding Ceremony Capture",
      "Professional Storytelling",
      "Authentic Moment Documentation",
      "Candid Photography",
      "Traditional Poses",
      "Drone Cinematography",
      "50-Page Wedding Album",
      "Full-Length Ceremony Video",
      "Emotional Highlight Reel",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ],
  },
  {
    id: "reception-elegance-package",
    idealFor: ["Reception"],
    name: "Reception Elegance Photography",
    category: "photography",
    subCategory: "Reception",
    price: 50000,
    setupCharges: 3000,
    deliveryCharges: 2000,
    rentalDuration: {
      minimum: "6 hours",
      standard: "8 hours",
    },
    description:
      "Capture the glamour and elegance of your wedding reception with sophisticated styling and emotional storytelling.",
    specifications: [
      "Glamorous Reception Moments",
      "Sophisticated Styling",
      "Emotional Storytelling",
      "Traditional Photography",
      "Candid Captures",
      "30-Page Luxury Album",
      "Full-Length Reception Video",
    ],
    available: true,
    image: [`${baseUrl}/Reception-image-1.jpg`],
  },
  {
    id: "pre-wedding-cinematic",
    idealFor: ["Weddings", "Haldi"],
    name: "Cinematic Pre-Wedding Experience",
    category: "photography",
    subCategory: "Pre Wedding",
    price: 40000,
    setupCharges: 2000,
    deliveryCharges: 1500,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
    },
    description:
      "A cinematic approach to capturing your love story before the wedding, with artistic location shoots and personalized narratives.",
    specifications: [
      "Romantic Storytelling",
      "Artistic Location Shoots",
      "Personalized Narrative",
      "Cinematic Photoshoot",
      "Artistic Edited Photos",
      "Cinematic Pre-Wedding Film",
      "Social Media Teasers",
    ],
    available: true,
    image: [
      `${baseUrl}/Pre-wedding-shoot-image-2.jpg`,
      `${baseUrl}/Pre-wedding-shoot-image-1.jpg`,
      `${baseUrl}/Pre-wedding-shoot-image-3.jpg`,
    ],
  },
  {
    id: "engagement-love-story",
    idealFor: ["Engagement"],
    name: "Engagement Love Story Package",
    category: "photography",
    subCategory: "Engagement",
    price: 30000,
    setupCharges: 2000,
    deliveryCharges: 1500,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
    },
    description:
      "Capture the intimate moments of your engagement with storytelling photography and cinematic invitation videos.",
    specifications: [
      "Intimate Moment Capturing",
      "Storytelling Photography",
      "Cinematic Invitation Video",
      "Candid Engagement Shots",
      "Traditional Portraits",
      "Edited Photo Collection",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ],
  },
  {
    id: "birthday-memory-maker",
    idealFor: ["Birthdays"],
    name: "Birthday Celebration Photography",
    category: "photography",
    subCategory: "Birthdays",
    price: 25000,
    setupCharges: 1500,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
    },
    description:
      "Capture the joy and energy of birthday celebrations with candid and cinematic photography.",
    specifications: [
      "Joyful Moment Capturing",
      "Energetic Event Coverage",
      "Emotional Storytelling",
      "Candid Birthday Shots",
      "Traditional Group Photos",
      "20-Page Album",
      "Cinematic Birthday Video",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ],
  },
  {
    id: "pr-event-narrative",
    idealFor: ["Others"],
    name: "PR Events Professional Coverage",
    category: "photography",
    subCategory: "PR Events",
    price: 60000,
    setupCharges: 3000,
    deliveryCharges: 2000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
    },
    description:
      "Professional coverage for PR events, ensuring brand storytelling and media-ready content.",
    specifications: [
      "Professional Event Documentation",
      "Brand Storytelling",
      "Media-Ready Content",
      "Candid Corporate Shots",
      "Drone Event Coverage",
      "Edited Professional Images",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ],
  },
  {
    id: "product-visual-storytelling",
    idealFor: ["Others"],
    name: "Product Photography Essentials",
    category: "photography",
    subCategory: "Products Photography",
    price: 20000,
    setupCharges: 1000,
    deliveryCharges: 500,
    rentalDuration: {
      minimum: "2 hours",
      standard: "4 hours",
    },
    description:
      "Creative photography services to showcase your products with professional styling and marketable visual content.",
    specifications: [
      "Creative Product Showcase",
      "Professional Styling",
      "Marketable Visual Content",
      "Creative Product Shots",
      "Studio and Lifestyle Images",
      "Multiple Angle Captures",
      "Product Showcase Video",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ],
  },
  {
    id: "private-moments-collection",
    idealFor: ["Private Parties", "Others"],
    name: "Private Events Intimate Photography",
    category: "photography",
    subCategory: "Private Events",
    price: 30000,
    setupCharges: 2000,
    deliveryCharges: 1500,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
    },
    description:
      "Capture the essence of private events with intimate photography that preserves cultural ceremonies and personal milestones.",
    specifications: [
      "Cultural Ceremony Documentation",
      "Emotional Moment Capturing",
      "Personal Milestone Preservation",
      "Traditional Ceremony Shots",
      "Candid Family Moments",
      "Cultural Detail Captures",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ],
  },

  // DECOR CATEGORY - SPECIAL EFFECTS
  // {
  //   id: "decor-fx-1",
  //   idealFor: "",
  //name: "CO2 Jets",
  //   category: "decor",
  //   subCategory: "Special Effects",
  //   price: 8000,
  //   setupCharges: 1500,
  //   deliveryCharges: 1000,
  //   rentalDuration: {
  //     minimum: "2 hours",
  //     standard: "4 hours",
  //     pricing: {
  //       hourly: 2000,
  //       daily: 12000,
  //     },
  //   },
  //   image: [
  //     "https://myutsav.s3.ap-south-1.amazonaws.com/Sharpies-one",
  //     "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
  //     "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
  //   ],
  //   description:
  //     "Ignite the excitement with our CO2 Jets, delivering high-impact effects that will leave your guests in awe during dramatic moments.",
  //   specifications: [
  //     "Set of 4 CO2 jets for maximum impact",
  //     "DMX controlled system for precise operation",
  //     "CO2 cylinder included for hassle-free use",
  //     "Professional operator to ensure flawless execution",
  //     "30-second continuous blast capability for stunning displays",
  //     "Wireless remote control for easy operation",
  //     "Safety barriers included for guest safety",
  //   ],
  //   available: true,
  // },
  // {
  //   id: "decor-fx-2",
  //   idealFor: "",
  // name: "Cold Fire Package",
  //   category: "decor",
  //   subCategory: "Special Effects",
  //   price: 12000,
  //   setupCharges: 2000,
  //   deliveryCharges: 1500,
  //   rentalDuration: {
  //     minimum: "2 hours",
  //     standard: "4 hours",
  //     pricing: {
  //       hourly: 3000,
  //       daily: 15000,
  //     },
  //   },
  //   image: [
  //     "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
  //     "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
  //   ],
  //   description:
  //     "Create a mesmerizing atmosphere with our Cold Fire Package, offering stunning fire displays that are safe for indoor use.",
  //   specifications: [
  //     "6 cold fire units for breathtaking effects",
  //     "DMX controller included for easy management",
  //     "Trained operator to ensure safety and quality",
  //     "Safety equipment provided for peace of mind",
  //     "Indoor and outdoor compatible for versatile use",
  //     "Multiple firing patterns for varied displays",
  //     "Emergency shutdown system for added safety",
  //   ],
  //   available: true,
  // },
  // {
  //   id: "decor-fx-3",
  //   idealFor: "",
  // name: "Bubble Show Package",
  //   category: "decor",
  //   subCategory: "Special Effects",
  //   price: 8000,
  //   setupCharges: 1500,
  //   deliveryCharges: 1000,
  //   rentalDuration: {
  //     minimum: "2 hours",
  //     standard: "4 hours",
  //     pricing: {
  //       hourly: 2000,
  //       daily: 12000,
  //     },
  //   },
  //   image: [
  //     "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
  //     "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
  //   ],
  //   description:
  //     "Delight your guests with our Bubble Show Package, featuring enchanting bubble effects that create a whimsical atmosphere.",
  //   specifications: [
  //     "Professional bubble machines (3 units) for maximum fun",
  //     "Smoke bubble capability for a magical touch",
  //     "LED bubble effects to dazzle your audience",
  //     "Special bubble solution for long-lasting bubbles",
  //     "Multiple pattern programs for varied displays",
  //     "DMX controller included for easy operation",
  //     "Trained operator for flawless execution",
  //     "Indoor/outdoor compatible for versatile use",
  //     "Setup time: 1 hour for quick enjoyment",
  //   ],
  //   available: true,
  // },
  // {
  //   id: "decor-fx-4",
  //   idealFor: "",
  //name: "Flower Shower System",
  //   category: "decor",
  //   subCategory: "Special Effects",
  //   price: 12000,
  //   setupCharges: 2000,
  //   deliveryCharges: 1500,
  //   rentalDuration: {
  //     minimum: "2 hours",
  //     standard: "4 hours",
  //     pricing: {
  //       hourly: 3000,
  //       daily: 15000,
  //     },
  //   },
  //   image: [
  //     "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
  //     "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
  //   ],
  //   description:
  //     "Add a touch of elegance with our Flower Shower System, perfect for creating unforgettable moments during your event.",
  //   specifications: [
  //     "4 flower shower units for stunning displays",
  //     "Fresh flower petals included for a natural touch",
  //     "Remote controlled operation for convenience",
  //     "Multiple shower patterns for varied effects",
  //     "Coverage area: 400 sq ft for maximum impact",
  //     "Indoor/outdoor compatible for versatile use",
  //     "Setup with truss system for stability",
  //     "Operator included for seamless execution",
  //     "Setup time: 2 hours for quick enjoyment",
  //   ],
  //   available: true,
  // },

  // ARTISTS CATEGORY
  {
    id: "artist-1",
    idealFor: [
      "Weddings",
      "Reception",
      "Haldi Cermony",
      "Private Parties",
      "Birthdays",
      "Anniversary",
      "Haldi",
      "House Warming",
      "Sangeeth",
      "Others",
    ],
    name: "Bridal Makeup Package",
    category: "artists",
    subCategory: "Makeup",
    price: 15000,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "3 hours",
      standard: "4 hours",
      pricing: {
        hourly: 5000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1630779374222-d8fc71997efb?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1604430456280-43f652c497aa?auto=format&fit=crop&q=80",
    ],
    description:
      "Transform into a vision of beauty with our Bridal Makeup Package, tailored to make your special day unforgettable.",
    specifications: [
      "HD makeup application for a flawless look",
      "Professional hair styling to complement your attire",
      "Saree or outfit draping for a perfect finish",
      "False lashes included for added glamour",
      "Touch-up kit provided for all-day perfection",
      "Trial session available to ensure your dream look",
      "Premium branded products used for quality assurance",
      "Assistant makeup artist included for personalized service",
    ],
    available: true,
  },

  {
    id: "artist-mehendi-1",
    idealFor: ["Weddings", "Sangeeth", "Birthdays", "Haldi", "Mehendi"],
    name: "Premium Bridal Mehendi",
    category: "artists",
    subCategory: "Mehendi",
    price: 15000,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
      pricing: {
        hourly: 3000,
      },
    },
    image: [
      `${baseUrl}/Mehendi-image-3.jpg`,
      `${baseUrl}/Mehendi-image-2.jpg`,

      `${baseUrl}/Mehendi-image-4.jpg`,
      `${baseUrl}/Mehendi-image-1.jpg`,
    ],
    description: "Premium bridal mehendi service with exclusive designs.",
    specifications: [
      "Expert mehendi artist",
      "Premium natural mehendi cones",
      "Exclusive design catalog",
      "Both hands and feet coverage",
      "Arabic and Indian designs",
      "Duration: 3-4 hours",
      "Touch-up service included",
      "Natural darkening tips",
      "Aftercare kit provided",
    ],
    available: true,
  },
  {
    id: "artist-hair-1",
    idealFor: [
      "Weddings",
      "Reception",
      "Sangeeth",
      "Birthdays",
      "Anniversary",
      "Private Parties",
      "Haldi",
      "Engagement",
    ],
    name: "Professional Hair Styling",
    category: "artists",
    subCategory: "Hair Styling",
    price: 8000,
    deliveryCharges: 500,
    rentalDuration: {
      minimum: "2 hours",
      standard: "3 hours",
      pricing: {
        hourly: 3000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description: "Professional hair styling service for all occasions.",
    specifications: [
      "Expert hair stylist",
      "Premium styling products",
      "Heat protection treatment",
      "Hair accessories included",
      "Multiple style options",
      "Pre-event consultation",
      "Touch-up kit provided",
      "Style duration: 6-8 hours",
      "Extension services available",
    ],
    available: true,
  },

  // TRANSPORTATION CATEGORY
  {
    id: "transport-1",
    idealFor: ["Weddings", "Corporate Events"],
    name: "Premium Wedding Car",
    category: "transportation",
    subCategory: "Cars",
    price: 10000,
    setupCharges: 1000,
    deliveryCharges: 1500,
    rentalDuration: {
      minimum: "4 hours",
      standard: "8 hours",
      pricing: {
        hourly: 2000,
        daily: 15000,
      },
    },
    image: [
      "https://i.postimg.cc/hG3Fg9tG/wedding-car-one.jpg",
      `${baseUrl}/Wedding-car-image-1.jpg`,
      `${baseUrl}/Wedding-car-image-2.jpg`,
      `${baseUrl}/Wedding-car-image-3.jpg`,
    ],
    description:
      "Arrive in style with our Premium Wedding Car service, featuring luxury vehicles and professional chauffeurs for a royal experience.",
    specifications: [
      "Premium sedan (Mercedes/BMW/Audi/Jaguar) for elegance",
      "Professional uniformed chauffeur for a classy touch",
      "Basic floral decoration included for a festive feel",
      // "Red carpet service for a grand entrance",
      "Fully air-conditioned for comfort",
      "Complimentary water bottles for your convenience",
      // "Fuel included for standard duration",
      "Insurance coverage included for peace of mind",
      "Backup vehicle on standby for emergencies",
    ],
    available: true,
  },
  {
    id: "transport-2",
    idealFor: ["Weddings", "Private Parties"],
    name: "Traditional Baggi/Chariot",
    category: "transportation",
    subCategory: "Special",
    price: 15000,
    setupCharges: 2000,
    deliveryCharges: 3000,
    rentalDuration: {
      minimum: "2 hours",
      standard: "4 hours",
      pricing: {
        hourly: 4000,
        daily: 25000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description:
      "Traditional horse-drawn chariot with royal decoration for wedding ceremonies.",
    specifications: [
      "Decorated royal chariot",
      "Trained horse with handler",
      "Professional chariot driver",
      "Elaborate floral decoration",
      "LED lighting setup",
      "Safety railings and steps",
      "Support staff (2 persons)",
      "Backup transportation arranged",
      "Traditional music system included",
    ],
    available: true,
  },

  // DECOR - LIGHTING CATEGORY
  {
    id: "decor-light-1",
    idealFor: ["Sangeeth", "Birthdays", "Anniversary", "Reception"],
    name: "LED Dance Floor",
    category: "decor",
    subCategory: "Lighting",
    price: 25000,
    setupCharges: 5000,
    deliveryCharges: 3000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
      pricing: {
        hourly: 5000,
        daily: 35000,
      },
    },
    image: [
      "https://i.postimg.cc/wTZjWVFV/LED-dance-floor-3.jpg",
      "https://i.postimg.cc/QMrxDd2K/led-dance-floor-1.jpg",
      "https://i.postimg.cc/qvKMW35d/LED-dance-floor-2.jpg",
    ],
    description:
      "Interactive LED dance floor with multiple patterns and color combinations.",
    specifications: [
      "16x16 ft standard size (customizable)",
      "RGB LED panels",
      "Multiple pattern animations",
      "Sound-reactive modes",
      "DMX controller included",
      "Non-slip surface",
      "Waterproof rating IP65",
      "Technical operator included",
      "Backup panels available",
      "Setup time: 3 hours",
    ],
    available: true,
  },
  // {
  //   id: "decor-light-2",
  //   idealFor: "",
  //   name: "Premium Backdrop Lighting",
  //   category: "decor",
  //   subCategory: "Lighting",
  //   price: 18000,
  //   setupCharges: 3000,
  //   deliveryCharges: 2000,
  //   rentalDuration: {
  //     minimum: "4 hours",
  //     standard: "6 hours",
  //     pricing: {
  //       hourly: 3500,
  //       daily: 25000,
  //     },
  //   },
  //   image: [
  //     "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&q=80",
  //     "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&q=80",
  //   ],
  //   description:
  //     "Complete backdrop lighting solution with premium effects and controls.",
  //   specifications: [
  //     "20x12 ft standard coverage",
  //     "RGB LED wall washers",
  //     "Moving head lights (4 units)",
  //     "Par LED lights (8 units)",
  //     "DMX controller with programs",
  //     "Wireless control system",
  //     "Multiple scene settings",
  //     "Emergency backup lights",
  //     "Technical operator included",
  //     "Setup time: 2 hours",
  //   ],
  //   available: true,
  // },

  // SUPPORT STAFF CATEGORY

  // SOUND - LIVE SOUND EQUIPMENT
  {
    id: "sound-live-1",
    idealFor: [
      "Weddings",
      "Birthdays",
      "Sangeeth",
      "Reception",
      "Anniversary",
      "Private Parties",
    ],
    name: "Comprehensive Live Band Setup",
    category: "sound",
    subCategory: "Live Sound",
    price: 24999,
    setupCharges: 5000,
    deliveryCharges: 3000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
      pricing: {
        hourly: 6000,
        daily: 45000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description:
      "A complete live band setup featuring professional sound equipment, ideal for concerts, events, and performances.",
    specifications: [
      "16-Channel Digital Mixer",
      "Wireless Microphones",
      "Wired Microphones",
      "Stage Monitors",
      "Main Speakers with Amplifiers",
      "DI Boxes for Instruments",
      "Comprehensive Cable Management",
      "Professional Sound Engineer Included",
      "Backup Equipment Available",
      "Stage setup also included",
      "Customization available",
      "Setup Time: Approximately 3 Hours",
    ],
    available: true,
  },

  {
    id: "sound-live-2",
    idealFor: ["Weddings", "Haldi"],
    name: "Traditional Nadaswaram Ensemble",
    category: "sound",
    subCategory: "Live Sound",
    price: 14999,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "2 hours",
      standard: "4 hours",
      pricing: {
        hourly: 4000,
        daily: 25000,
      },
    },
    image: [
      "https://i.postimg.cc/zvfGQ29d/Nadaswaram-Group.jpg",
      "https://i.postimg.cc/j28LdYH0/Nadaswaram-Group-2.jpg",
    ],
    description:
      "Experience the rich cultural heritage with our traditional Nadaswaram ensemble, perfect for auspicious ceremonies and celebrations.",
    specifications: [
      "Professional 4-Member Ensemble",
      "Traditional Costumes",
      "2 Nadaswaram Players",
      "2 Thavil Players",
      "Repertoire of Traditional and Modern Music",
      "Experienced in Wedding Ceremonies",
      "Backup Artists Available",
      "Additional Musicians Can Be Accommodated Upon Request",
    ],
    available: true,
  },

  // DECOR - FURNITURE
  // {
  //   id: "decor-furn-1",
  //   idealFor: "",
  //   name: "Premium Sofa Set",
  //   category: "decor",
  //   subCategory: "Furniture",
  //   price: 12000,
  //   setupCharges: 2000,
  //   deliveryCharges: 2500,
  //   rentalDuration: {
  //     minimum: "24 hours",
  //     standard: "24 hours",
  //     pricing: {
  //       daily: 12000,
  //     },
  //   },
  //   image: [
  //     "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
  //     "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
  //   ],
  //   description: "Luxury sofa set for wedding stage and VIP areas.",
  //   specifications: [
  //     "3-seater royal sofa (2 units)",
  //     "Single-seater chairs (4 units)",
  //     "Premium fabric upholstery",
  //     "Matching center tables",
  //     "Side tables (4 units)",
  //     "Decorative cushions included",
  //     "Carpet area included",
  //     "Setup and arrangement",
  //     "Backup furniture available",
  //   ],
  //   available: true,
  // },
  // {
  //   id: "decor-furn-2",
  //   idealFor: [],
  //   name: "Complete Stage Setup",
  //   category: "decor",
  //   subCategory: "Furniture",
  //   price: 45000,
  //   setupCharges: 8000,
  //   deliveryCharges: 5000,
  //   rentalDuration: {
  //     minimum: "24 hours",
  //     standard: "24 hours",
  //     pricing: {
  //       daily: 45000,
  //     },
  //   },
  //   image: [
  //     "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
  //     "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
  //   ],
  //   description:
  //     "Complete wedding stage setup with premium furniture and decor.",
  //   specifications: [
  //     "24x16 ft raised platform",
  //     "Premium backdrop with lighting",
  //     "Royal sofa set for couple",
  //     "Side seating arrangements",
  //     "Floral decoration",
  //     "LED accent lighting",
  //     "Carpet and walkway",
  //     "Photo opportunity areas",
  //     "Setup time: 6 hours",
  //     "Professional decor team",
  //   ],
  //   available: true,
  // },

  // DECOR - SPECIAL EFFECTS
  // {
  //   id: "decor-fx-3",
  //   idealFor: "",
  //   name: "Bubble Show Package",
  //   category: "decor",
  //   subCategory: "Special Effects",
  //   price: 8000,
  //   setupCharges: 1500,
  //   deliveryCharges: 1000,
  //   rentalDuration: {
  //     minimum: "2 hours",
  //     standard: "4 hours",
  //     pricing: {
  //       hourly: 2000,
  //       daily: 12000,
  //     },
  //   },
  //   image: [
  //     "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
  //     "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
  //   ],
  //   description: "Professional bubble show with multiple effects and machines.",
  //   specifications: [
  //     "Professional bubble machines (3 units)",
  //     "Smoke bubble capability",
  //     "LED bubble effects",
  //     "Special bubble solution",
  //     "Multiple pattern programs",
  //     "DMX controller included",
  //     "Trained operator",
  //     "Indoor/outdoor compatible",
  //     "Setup time: 1 hour",
  //   ],
  //   available: true,
  // },
  // {
  //   id: "decor-fx-4",
  //   idealFor: "",
  //   name: "Flower Shower System",
  //   category: "decor",
  //   subCategory: "Special Effects",
  //   price: 12000,
  //   setupCharges: 2000,
  //   deliveryCharges: 1500,
  //   rentalDuration: {
  //     minimum: "2 hours",
  //     standard: "4 hours",
  //     pricing: {
  //       hourly: 3000,
  //       daily: 15000,
  //     },
  //   },
  //   image: [
  //     "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
  //     "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
  //   ],
  //   description: "Automated flower shower system for special moments.",
  //   specifications: [
  //     "4 flower shower units",
  //     "Fresh flower petals included",
  //     "Remote controlled operation",
  //     "Multiple shower patterns",
  //     "Coverage area: 400 sq ft",
  //     "Indoor/outdoor compatible",
  //     "Setup with truss system",
  //     "Operator included",
  //     "Setup time: 2 hours",
  //   ],
  //   available: true,
  // },

  // SUPPORT STAFF - HOSPITALITY
  {
    id: "staff-hosp-1",
    idealFor: ["Weddings", "Sangeeth", "Birthdays", "Reception"],
    name: "Welcome Staff Team",
    category: "support-staff",
    subCategory: "Hospitality",
    price: 12000,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "6 hours",
      pricing: {
        hourly: 2000,
        daily: 15000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description: "Professional welcome staff team for events.",
    specifications: [
      "6 trained staff members",
      "Professional uniforms",
      "Guest management expertise",
      "Multi-lingual capabilities",
      "Coordination with event team",
      "Welcome drink service",
      "Guest list management",
      "Emergency handling trained",
    ],
    available: true,
  },
  {
    id: "staff-security-1",
    idealFor: [
      "Weddings",
      "Reception",
      "Sangeeth",
      "Birthdays",
      "Corporate Events",
      "Others",
    ],
    name: "Event Security Team",
    category: "support-staff",
    subCategory: "Security",
    price: 10000,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "6 hours",
      standard: "8 hours",
      pricing: {
        hourly: 1500,
        daily: 12000,
      },
    },
    image: [
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80",
    ],
    description: "Professional security team for event safety.",
    specifications: [
      "4 trained security guards",
      "1 supervisor",
      "Professional uniforms",
      "Security equipment",
      "Crowd management trained",
      "Emergency protocols",
      "CCTV monitoring",
      "Parking management",
      "VIP security available",
    ],
    available: true,
  },

  // DECOR - EVENT DECOR

  // Lighting Products
  {
    id: "lighting-house-weddings",
    idealFor: ["Weddings", "House Warming", "Festivals"],
    name: "House Lighting",
    category: "lighting",
    subCategory: "Weddings",
    price: 20000,
    setupCharges: 3000,
    deliveryCharges: 1500,
    rentalDuration: {
      minimum: "4 hours",
      standard: "8 hours",
      pricing: {
        hourly: 5000,
        daily: 20000,
      },
    },
    description:
      "Elegant lighting solutions for weddings, creating a romantic and festive atmosphere.",
    specifications: [
      "LED string lights",
      "Spotlights for key areas",
      "Color-changing options",
      "Setup for indoor and outdoor",
      "Professional installation included",
    ],
    available: true,
    image: [
      `${baseUrl}/House+Lighting+Decor+-3.jpg`,
      `${baseUrl}/House+Lighting+Decor.jpg`,
      `${baseUrl}/House+Lighting+Decor+-2.jpg`,
    ], // Replace with actual image URL
  },
  {
    id: "lighting-festive",
    idealFor: ["Festivals"],
    name: "Festive Lighting",
    category: "lighting",
    subCategory: "Festive",
    price: 15000,
    setupCharges: 2000,
    deliveryCharges: 1000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "8 hours",
      pricing: {
        hourly: 4000,
        daily: 15000,
      },
    },
    description:
      "Vibrant lighting solutions for festive occasions, enhancing the celebratory mood.",
    specifications: [
      "Colorful LED lights",
      "Decorative lanterns",
      "String lights for outdoor use",
      "Setup for various festive themes",
      "Professional installation included",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ], // Replace with actual image URL
  },
  {
    id: "lighting-personal-events",
    idealFor: [],
    name: "Personal Events Lighting",
    category: "lighting",
    subCategory: "Personal Events",
    price: 18000,
    setupCharges: 2500,
    deliveryCharges: 1200,
    rentalDuration: {
      minimum: "4 hours",
      standard: "8 hours",
      pricing: {
        hourly: 4500,
        daily: 18000,
      },
    },
    description:
      "Customized lighting solutions for personal events, tailored to your needs.",
    specifications: [
      "LED uplighting",
      "Mood lighting options",
      "Thematic decorations",
      "Setup for indoor and outdoor",
      "Professional installation included",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ], // Replace with actual image URL
  },
  {
    id: "lighting-event-venue",
    idealFor: ["Weddings", "Reception", "Sangeeth", "Engagement"],
    name: "Event Venue Lighting",
    category: "lighting",
    subCategory: "Event Venue",
    price: 25000,
    setupCharges: 4000,
    deliveryCharges: 2000,
    rentalDuration: {
      minimum: "4 hours",
      standard: "8 hours",
      pricing: {
        hourly: 6000,
        daily: 25000,
      },
    },
    description:
      "Comprehensive lighting solutions for event venues, ensuring a captivating ambiance.",
    specifications: [
      "Stage lighting",
      "Ambient lighting",
      "Spotlights for key areas",
      "Customizable lighting setups",
      "Professional installation included",
    ],
    available: true,
    image: [
      `${baseUrl}/Venue-lighting-image-1.jpg`,
      `${baseUrl}/Venue-lighting-image-3.jpg`,
      `${baseUrl}/Venue-lighting-image-4.jpg`,
      `${baseUrl}/Venue-lighting-image-2.jpg`,
    ], // Replace with actual image URL
  },
  {
    id: "lighting-shops-businesses",
    idealFor: ["Others"],
    name: "Shops/Businesses Lighting",
    category: "lighting",
    subCategory: "Shops/Businesses",
    price: 22000,
    setupCharges: 3500,
    deliveryCharges: 1500,
    rentalDuration: {
      minimum: "4 hours",
      standard: "8 hours",
      pricing: {
        hourly: 5500,
        daily: 22000,
      },
    },
    description:
      "Professional lighting solutions for shops and businesses, enhancing visibility and appeal.",
    specifications: [
      "LED display lighting",
      "Track lighting for products",
      "Energy-efficient options",
      "Setup for indoor and outdoor",
      "Professional installation included",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ], // Replace with actual image URL
  },
  {
    id: "lighting-temple-pandals",
    idealFor: ["Festivals", "Others"],
    name: "Temple/Pandals Lighting",
    category: "lighting",
    subCategory: "Temple/Pandals",
    price: 20000,
    setupCharges: 3000,
    deliveryCharges: 1500,
    rentalDuration: {
      minimum: "4 hours",
      standard: "8 hours",
      pricing: {
        hourly: 5000,
        daily: 20000,
      },
    },
    description:
      "Specialized lighting solutions for temples and pandals, creating a divine atmosphere.",
    specifications: [
      "Traditional decorative lights",
      "LED lights for vibrant displays",
      "Setup for religious events",
      "Professional installation included",
      "Customizable lighting themes",
    ],
    available: true,
    image: [
      "https://i.postimg.cc/tJW8hwt1/Decor.jpg",
      "https://i.postimg.cc/N0nnZBd9/Stage-Design.jpg",
    ], // Replace with actual image URL
  },
];

//Welcome to Utsav, where we redefine event planning! Our mission is to make organizing unforgettable celebrations a breeze without compromising on quality or flair. Choose from our customizable event packages that cover everything from sound & visuals to decor, photography, transportation, artists, and supporting staff. While our prices reflect the premium quality of our services, once you experience Utsav, you’ll keep coming back for more! We carefully select a limited number of trusted vendors to ensure the best service and seamless coordination. Enjoy your special moments with family and friends while we handle the rest. Your satisfaction is our top priority, and we welcome your feedback to help us grow and improve. Let's make your next event magical together!
